### ISSUE TITLE
Touches go through Navigation Drawer

### ISSUE THREAD

**Issue by PaoloRotolo** [googlesamples/android-UniversalMusicPlayer#1]
Steps to reproduce:
1. Open the app;
2. Open the Navigation Drawer;
3. Tap on the blue image at top;

You'll notice that you've actually selected an item of the ListView below the drawer.

![screenshot_2015-03-12-19-00-25](https://cloud.githubusercontent.com/assets/5623301/6624641/e28d576c-c8ea-11e4-8bdb-7683f22459f1.png)

**Comment by afollestad** [comment]
A simple fix is making that header clickable, either with an OnClickListener or by intercepted simple touch events.

**Comment by PaoloRotolo** [comment]
Thanks @afollestad! I've already proposed a merge that intercept clicks in the Drawer container simpy with:

```
android:clickable="true"
```

**Comment by afollestad** [comment]
Oh nice, much simpler

**Comment by erickmendonca** [comment]
@PaoloRotolo :+1:
