### ISSUE TITLE
Error:Error: File path too long on Windows, keep below 240 characters 

### ISSUE THREAD

**Issue by lsw645** [googlesamples/android-UniversalMusicPlayer#100]
When I import the project ,it shows me Error:Error: File path too long on Windows, keep below 240 characters : D:\project\android-UniversalMusicPlayer-master\android-UniversalMusicPlayer-master\mobile\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.4.0\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
 I have tried to rename the common_google_signin_btn_icon_dark_disabled.9.png,but it didn't work;
how to solve this question?

**Comment by rameshakulapc** [comment]
Change the folder names are small.

**Issue** : Android studio Error File Path too long on Windows keep below 240 characters

**Solution**:

allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
}

**Comment by Stepan222** [comment]
Long path error is a very common problem in Windows users face. Try using Long Path Tool if your computer is giving errors like, “Path too long”, “Path too long – aborting (error code 80/1)”, 0x80010135 Path too long”, “Error cannot delete file: cannot read from source file or disk” or “File cannot be copied”. You can use Long Path Tool to resolve these problems.

**Comment by SergiyMike** [comment]
You can try "Long Path Tool" as it deletes, copies and renames files/folders those have long paths. I personally found all of these functions working with great success. :)

**Comment by marta12445** [comment]
Hello guys,
you can use "**Long Path Tool**" software program to solve this problem.

**Comment by amitParate** [comment]
"Long Path Tool" is better to use and get good result.

**Comment by liona1982** [comment]
Try Duplicate Files Deleter as it can remove any problems that you might have.

**Comment by amitParate** [comment]
Hello Liona,
This is Amit Parate I have good experience of in data entry, website
development and desing,
can you help me I am seeking a client to provide me work on there condition
I am ready to work in low rate also please help me.
Best Regards
Amit Parate

**Comment by liona1982** [comment]
please give me your skype ID

**Comment by amitParate** [comment]
amitskype251

**Comment by amitParate** [comment]
Hi,
Did you get my Skype ID?
Please reply me.

**Comment by liona1982** [comment]
i already added you but no response from your end on skype

**Comment by amitParate** [comment]
Hey Liona,
Thank for reply me.
Oh yes I will chat with you on skype.
Thanks & Best Regards
Amit Parate

**Comment by amitParate** [comment]
Hey Liona,
I am online now, can we chat?

**Comment by amitParate** [comment]
Please send me message on skype.

**Comment by amitParate** [comment]
Hi Liona,
This is Amit Parate I am looking an opportunity to work in data processing
or back office at low rate.
Would you suggest me something for it.
Thanks & Best Regards
Amit Parate
