### ISSUE TITLE
universalmusicplayer

### ISSUE THREAD

**Issue by telvenes** [googlesamples/android-UniversalMusicPlayer#108]
Hi,

Can someone help me to remove all of the code that are not in use?
Seeing that example Favourites is in code, but as far as I know, this is not in use.

Trying really hard to understand the code, but it is difficult for us beginners.

**Comment by nic0lette** [comment]
Hi. I'd recommend checking out the codelab [Playing music on cars and wearables](https://codelabs.developers.google.com/codelabs/android-music-player/index.html). The codelab walks through the process of converting an app that directly uses MediaPlayer to play music to one that uses a Service and the MediaSession objects.

(You could also skip and just load the "final" project of the code [from the repo](https://github.com/googlecodelabs/android-wear-auto-uamp) if you just want to see a simpler (and less featureful) app than UAMP.
