### ISSUE TITLE
Can't run it. The error says "Error:No cached version of com.android.tools.build:gradle:1.1.0 available for offline mode. Disable Gradle 'offline mode' and sync project"

### ISSUE THREAD

**Issue by an631ac** [googlesamples/android-UniversalMusicPlayer#11]
When I disabled the "offline mode" the error says
"Error:Unknown host 'jcenter.bintray.com'.
Enable Gradle 'offline mode' and sync project. Learn about configuring HTTP proxies in gradle"

What should I do?

Thank you

**Comment by mangini** [comment]
This doesn't look like an issue on UniversalMusicPlayer. I've found this thread on StackOverflow, hope it helps: http://stackoverflow.com/questions/19678137/create-new-project-on-android-error-studio-unknown-host-services-gradle-org

**Comment by RohitLuthra19** [comment]
**i am also facing similar kind of problem.**
Error:No cached version of com.android.tools.build:gradle:1.2.3 available for offline mode.
<a href="toggle.offline.mode">Disable Gradle 'offline mode' and sync project</a>

**Comment by sudheerkumarnokku** [comment]
i am facing this error
i am a basic android developer 
please help me for this error
Error:No cached version listing for io.fabric.tools:gradle:1.+ available for offline mode.

**Comment by roshaplus** [comment]
repositories {
        jcenter()
        mavenCentral()

**Comment by YuriyBereguliak** [comment]
I was faced with the same issue, when my internet connection is really bad. When the connection has been restored, everything is working.

**Comment by niranjan-magare1997** [comment]
Make sure you have internet connection.

1) Change your gradle version to any other version from build.gradle file and sync your project.
2) If you wish to build your project with the same version you were getting error for then follow above step and  rebuild your project by entering your previsous version.
 This worked for me.

**Comment by abhimangalms** [comment]
Same this is happenig to me.
_Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:support-v4:28.1.0.
Disable offline mode and sync project_

same issue is happening after **disabling the offline mode**
