### ISSUE TITLE
How can we add more Genres on screen one?

### ISSUE THREAD

**Issue by mrbankim** [googlesamples/android-UniversalMusicPlayer#117]
In this application, after launch the app we are getting 
Screen 1: Genres 
Screen 2: List of Genres like (rock, cinematic, jazz n blue)
Screen 3: List of Songs (under particular Genre) 

My question is how can we get more Genres in Screen 1. Like bellow, and click on Genres1 we should get child list of Genres1 (modern, classic etc or could be anything)

So the screen one should be like below item list and click on this item list we should get child list.

Screen 1 : Genres 1
                 Genres 2
                 Genres 3

I have tried to modify the json structure but not able to success on this. Is there anyone can help me on this.

Tank you.

**Comment by basicn3** [comment]
would very much like a response to this

**Comment by nic0lette** [comment]
Something like:
Genres > Rock >
Blues Rock
Progressive Rock
Modern Rock

I.e.: Nested genres?

**Comment by mrbankim** [comment]
It should be like in first page Genres list. like below.
Genres1
Genres2
Genres3
Genres4

once click on Genres1, should get list of sub Genres, like below.

Genres1 -> sub Genres1
              -> sub Genres2
              -> sub Genres3
