### ISSUE TITLE
Android Auto is not seeing it

### ISSUE THREAD

**Issue by ionutcristea** [googlesamples/android-UniversalMusicPlayer#123]
Seems like android auto application don't see and control this player.

**Comment by mikeseif** [comment]
Android Auto hardware / handset app will only display the app when published through the Play Store.  You can test using the Desktop Head Unit emulator, see here for full details:
https://developer.android.com/training/auto/testing/index.html

**Comment by nic0lette** [comment]
Please check out [this codelab](https://codelabs.developers.google.com/codelabs/android-music-player/index.html#6) which should be able to help you test this software with Android Auto.
