### ISSUE TITLE
解决No acceptable module found的问题。

### ISSUE THREAD

**Issue by sshhsun-code** [googlesamples/android-UniversalMusicPlayer#125]
在手机上编译好这个音乐项目后，打开会闪退，找了解决办法好久都没方法
我的手机是魅族手机，在魅族的应用市场中搜索“谷歌安装器魅族专用"后，将相关的服务安装好，同时手机翻墙，再打开这个app就不会闪退了，至于具体的代码原因，目前还没有看源码，等看完源码后来再继续补充。。。。。。

**Comment by yuhaodev** [comment]
same problem!when application start running,it crash immediately! my phone is HUAWEI CAM-AL00.
android 6.0

**Comment by nic0lette** [comment]
Sorry, but I'm not able to quite understand your comment, even while using Google Translate. If you could comment in English, or provide a stack trace, I can take a look, but until then I'm going to close this.

**Comment by sshhsun-code** [comment]
your phone has to connect to Google Service to make sure the app  working regularly。And you should install Google AppStore to confirm to Google Service.
