### ISSUE TITLE
Upgrade to Android SdkVersion 25 compile errors

### ISSUE THREAD

**Issue by devshisiyani** [googlesamples/android-UniversalMusicPlayer#127]
Using Android Studio version 2.2.3
updated build.gradle file
Upgrade to compileSdkVersion 25 and buildToolsVersion "24.0.3"
Upgrade to java JavaVersion.VERSION_1_8

I get compilation error
Error: mobile\src\main\java\com\example\android\uamp\playback\CastPlayback.java:324.19: The type CastPlayback.CastMediaClientListener must implement the inherited abstract method RemoteMediaClient.Listener.onAdBreakStatusUpdated()

Help required to resolve the compilation  error 
Complete file
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "24.0.3"

    defaultConfig {
        applicationId "com.example.android.uamp"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 2
        versionName "1.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        jackOptions {
            enabled true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        javaMaxHeapSize "2g"
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile 'com.google.android.gms:play-services-cast-framework:10.0.1'
    compile 'com.google.android.support:wearable:1.4.0'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support:cardview-v7:25.0.0'
    compile 'com.android.support:mediarouter-v7:25.0.0'
    compile 'com.android.support:leanback-v17:25.0.0'
    compile 'com.android.support:design:25.0.0'
}

**Comment by jianinz** [comment]
It says `The type CastPlayback.CastMediaClientListener must implement the inherited abstract method RemoteMediaClient.Listener.onAdBreakStatusUpdated()`

So you need to implement `onAdBreakStatusUpdated()`

~~~~java
private RemoteMediaClient.Listener remoteMediaClientListener = new RemoteMediaClient.Listener() {
        @Override public void onStatusUpdated() {
            
        }

        @Override public void onMetadataUpdated() {

        }

        @Override public void onQueueStatusUpdated() {

        }

        @Override public void onPreloadStatusUpdated() {

        }

        @Override public void onSendingRemoteMediaRequest() {

        }

        @Override public void onAdBreakStatusUpdated() {

        }
    };
~~~~

**Comment by nic0lette** [comment]
I've recently updated compileSdkVersion to 25, but since [Jack was deprecated](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html), I'm leaving the compile options to use/generate Java 1.7 code until Java 1.8 is fully supported in Android Studio.
