### ISSUE TITLE
Getting Media Player error -38 (0)

### ISSUE THREAD

**Issue by praneethalla93** [googlesamples/android-UniversalMusicPlayer#136]
When I click on any song for the first time it works but if i click on next or any other song immediately, It stops playing and throws this error Media Player error -38 (0). Does anyone has idea why this is happening?

**Comment by zakharhabib** [comment]
I would like an answer to this aswell.

**Comment by nic0lette** [comment]
What Android version is it? Would you be able to provide a log? (I tried briefly to reproduce this, but haven't had any luck with my devices.)

**Comment by zakharhabib** [comment]
Android version is 23.
This is the log of the code.

`04-08 00:47:06.942 2527-2527/? I/art: Late-enabling -Xcheck:jni
04-08 00:47:07.208 2527-2527/com.example.android.uamp W/System: ClassLoader referenced unknown path: /data/app/com.example.android.uamp-2/lib/arm
04-08 00:47:07.215 2527-2527/com.example.android.uamp I/InstantRun: Instant Run Runtime started. Android package is com.example.android.uamp, real application class is null.
04-08 00:47:12.280 2527-2527/com.example.android.uamp W/System: ClassLoader referenced unknown path: /data/app/com.example.android.uamp-2/lib/arm
04-08 00:47:12.834 2527-2562/com.example.android.uamp W/art: Suspending all threads took: 117.061ms
04-08 00:47:12.841 2527-2527/com.example.android.uamp W/art: Verification of void com.example.android.uamp.ui.BaseActivity.onCreate(android.os.Bundle) took 176.032ms
04-08 00:47:13.503 2527-2527/com.example.android.uamp I/MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Phone, description=null, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=15, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
04-08 00:47:13.820 2527-2562/com.example.android.uamp W/art: Suspending all threads took: 100.717ms
04-08 00:47:13.836 2527-2572/com.example.android.uamp I/art: Background sticky concurrent mark sweep GC freed 37159(3MB) AllocSpace objects, 15(740KB) LOS objects, 26% free, 17MB/23MB, paused 1.282ms total 183.018ms
04-08 00:47:14.045 2527-2527/com.example.android.uamp I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:7
04-08 00:47:14.045 2527-2527/com.example.android.uamp I/DynamiteModule: Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 7
04-08 00:47:14.080 2527-2527/com.example.android.uamp W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/0000001d/n/armeabi-v7a
04-08 00:47:14.081 2527-2527/com.example.android.uamp W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/0000001d/n/armeabi
04-08 00:47:14.159 2527-2527/com.example.android.uamp I/CastDynamiteModuleImpl: zb created by ClassLoader bzi[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/0000001d/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/0000001d/n/armeabi-v7a, /data/user/0/com.google.android.gms/app_chimera/m/0000001d/n/armeabi, /vendor/lib, /system/lib]]].
04-08 00:47:14.639 2527-2527/com.example.android.uamp W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-08 00:47:14.730 2527-2562/com.example.android.uamp W/art: Suspending all threads took: 9.502ms
04-08 00:47:15.688 2527-2935/com.example.android.uamp D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-08 00:47:15.819 2527-2935/com.example.android.uamp I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-08 00:47:15.885 2527-2935/com.example.android.uamp I/OpenGLRenderer: Initialized EGL, version 1.4
04-08 00:47:16.512 2527-2527/com.example.android.uamp I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
04-08 00:47:23.249 2527-2572/com.example.android.uamp I/art: Background partial concurrent mark sweep GC freed 26809(2MB) AllocSpace objects, 20(1192KB) LOS objects, 40% free, 19MB/32MB, paused 5.088ms total 106.819ms
04-08 00:47:51.504 2527-2572/com.example.android.uamp I/art: Background partial concurrent mark sweep GC freed 5069(343KB) AllocSpace objects, 8(596KB) LOS objects, 40% free, 19MB/32MB, paused 8.392ms total 37.611ms
04-08 00:47:51.900 2527-2935/com.example.android.uamp V/RenderScript: 0x96477000 Launching thread(s), CPUs 4
**04-08 00:48:11.912 2527-3724/com.example.android.uamp E/MediaPlayer: error (1, -2147483648)
04-08 00:48:11.928 2527-2527/com.example.android.uamp E/MediaPlayer: Error (1,-2147483648)
04-08 00:48:11.928 2527-2527/com.example.android.uamp E/uamp_LocalPlayback: Media player error: what=1, extra=-2147483648**`

**Comment by nic0lette** [comment]
This means that the file wasn't located. It's usually a result of changing the JSON's location without updating the URLs of the media files correctly. This usually means putting the JSON in `https://www.example.com/music.json`, with media files that say something like `my_song.mp3`, but `my_song.mp3` is on `https://music.example.com/my_song.mp3`. In this case `source` should be set to `https://music.example.com/my_song.mp3` rather than `my_song.mp3`.
