### ISSUE TITLE
The code gives a Media Player error -38 (0)

### ISSUE THREAD

**Issue by zakharhabib** [googlesamples/android-UniversalMusicPlayer#146]
I want to add more songs to the catalog so I added my custom URL to the catalog which is  
 'https://raw.githubusercontent.com/zakharhabib/hello-world/master/musiclibrary.json'
after i change the link of the catalog to this url it gives me the 'Media Player error -38 (0)'

**Comment by IonutPopescuRO** [comment]
One example:
`	{ "title" : "Jazz in Paris",
	  "album" : "Jazz & Blues",
	  "artist" : "Media Right Productions",
	  "genre" : "Jazz & Blues",
	  "source" : "Jazz_In_Paris.mp3",
	  "image" : "album_art.jpg",
	  "trackNumber" : 1,
	  "totalTrackCount" : 6,
	  "duration" : 103,
	  "site" : "https://www.youtube.com/audiolibrary/music"
	}`
if "source" start with http will take song from the link else will be: (CATALOG_URL) https://raw.githubusercontent.com/zakharhabib/hello-world/master/"Jazz_In_Paris.mp3"

**Comment by nic0lette** [comment]
This error means the music file couldn't be loaded, which is likely related to what @IonutPopescuRO wrote above.
