### ISSUE TITLE
GridViews and Lists

### ISSUE THREAD

**Issue by arushk1** [googlesamples/android-UniversalMusicPlayer#15]
1)  I can currently set the icon for media items by checking if they are playable or not. 
How can I set a thumbnail on the browsable items like Genre lists, by taking an album art at random from its child.

2) How can I differentiate between browsable and media items? So I can set a grid layout for browsable items and a list for media items

3) The play by voice search worked for the first time only. Subsequent times it searches the web.

4) How to add a button for random playlist generation using the random function on QueueHelper

**Comment by mangini** [comment]
The `children` param passed to [MediaBrowser.SubscriptionCallback.onChildrenLoaded](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/ui/MediaBrowserFragment.java#L111) is a List of MediaItem's. MediaItem has two methods: `isPlayable` and `isBrowsable`.

However, remember that there is nothing preventing both browsable and playable items to be mixed at the same level. If, for your application, you know this wouldn't happen, then you can get the result of onChildrenLoaded, check one or all of the children and change the layout appropriately.

**Comment by arushk1** [comment]
There are a few more issue, I added just now. Please have a look.

**Comment by arushk1** [comment]
Is there another way to check this in the onCreate method of MediaBrowserFragment?
