### ISSUE TITLE
Looping single and multiple songs

### ISSUE THREAD

**Issue by aravindnaidu09** [googlesamples/android-UniversalMusicPlayer#153]
How to do looping using this player?

**Comment by anhtuannd** [comment]
I handled looping by adding some condition in onCompletion () of PlaybackManager.

**Comment by nic0lette** [comment]
The latest version supports looping + shuffle out of the box by calling `transportControls.setRepeatMode(repeatMode)` and `transportControls.setShuffleMode(shuffleMode)` respectively.

There isn't a UI associated with that at the moment, but those methods work via the `MediaSessionConnection` class, so shouldn't be difficult to connect up.
