### ISSUE TITLE
BUG: The onLoadChildren method cannot be executed

### ISSUE THREAD

**Issue by firsthubgit** [googlesamples/android-UniversalMusicPlayer#155]
When I press the home key, switch the app to the background and then switch to the foreground. click the  "Genres" item， The onLoadChildren method cannot be called。。。why???

**Comment by firsthubgit** [comment]
oh， new BrowserRoot(MEDIA_ID_ROOT, null)。here cannot be null.......

**Comment by firsthubgit** [comment]
mRootHints {EXTRA_CLIENT_VERSION:CLIENT_VERSION_CURRENT},
the value of mRootHints is removed，so when switch to the foreground，The Service cant return the MessagerImpl，therefor i cannot registerCallbackMessenger() , i cannot subscribe successfully。。
is  that  the bug of support-v4 ????

**Comment by nic0lette** [comment]
Sorry, but I'm not sure exactly what you mean. I suspect it may be fixed with the latest version of the support library (which I just updated the project to)?

**Comment by firsthubgit** [comment]
the latest version of the support library doesnt work. The MusicService should run in another process. It dose work.

**Comment by nic0lette** [comment]
Running the MusicService in a separate process isn't supported, for the very least reason that the Cast SDK doesn't support multiprocess playback.
