### ISSUE TITLE
Unable to implement Looping, Shuffle Functionality using MediaSessionCompat Callback

### ISSUE THREAD

**Issue by simmikava** [googlesamples/android-UniversalMusicPlayer#157]
FLAG_HANDLES_QUEUE_COMMANDS is enabled for API 25 and above. So how can we implement looping and shuffle functionality through MediaSessionCompat callback? Is it that we have to manage the queue manually for API < 25 ?

**Comment by anhtuannd** [comment]
FLAG_HANDLES_QUEUE_COMMANDS  is only for addQueueItem and removeQueueItem, I think so.

**Comment by nic0lette** [comment]
This should be working the same as #153 now.
