### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by arushk1** [googlesamples/android-UniversalMusicPlayer#16]
1) I can currently set the icon for media items by checking if they are playable or not.
How can I set a thumbnail on the browsable items like Genre lists, by taking an album art at random from its child

2) The play by voice search worked for the first time only. Subsequent times it searches the web.

3) How to add a button for random playlist generation using the random function on QueueHelper

**Comment by mangini** [comment]
Please, open one issue per issue, so it can be tracked appropriately. For generic questions like 1) and 3), please use StackOverflow (if you want, ping me on G+ with the StackOverflow question, so I can respond it faster)

1) you set whatever art you want on your MediaItem's. See, for example, [this](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MusicService.java#L331).

2) What's the query you've tried? Where are you searching from? I'm closing this issue, but please open another one with this item and more information, like Android version, Play Services version, etc.

3) If you want to maintain the decoupling between MediaSession and its consumers (UI, Android Auto, Wear, etc), you can add a "shuffle" custom action [here](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MusicService.java#L694) and handle on [onCustomAction](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MusicService.java#L491). Then, in your UI (for example, in PlaybackControlsFragment), you check the PlaybackState custom actions and, if there is one with a known shuffle ID, you add the proper button that, when clicked, calls onCustomAction on the MediaController.TransportControls. If you want to make it even fancier, you can show buttons for all available custom actions without even knowing what they are about (CustomAction class contains a string and an icon, so the consumer doesn't need to know its semantic on coding time).
