### ISSUE TITLE
App crashes at launch

### ISSUE THREAD

**Issue by AbanoubG** [googlesamples/android-UniversalMusicPlayer#162]
So I had the application running perfectly until I changed some hosting things with my Hosting company. The app now crashes everytime I tap on the first page. It does not even populate the json file. I tried going back and replacing RemoteSource with the original Google one and even that one makes the application crash. Any ideas on how to fix this?

This is where my json file is located
http://copticchurch-library.org/hymns-media/media.json
and this is what my server looks like with the files https://ibb.co/naPRXF

**Comment by anhtuannd** [comment]
Maybe there will be more help if you can provide crash log.

**Comment by mrTosinAmuda** [comment]
This url http://copticchurch-library.org/hymns-media/media.json is not returning JSON it is returning HTML

**Comment by nic0lette** [comment]
Sorry, but as @mrTosinAmuda wrote, this URL isn't returning JSON, so it isn't being parsed correctly. You'll need to fix that and then UAMP should work for you.

**Comment by AbanoubG** [comment]
Weird thing is, it works fine on Android 7.0 however 8.o crashes the app
