### ISSUE TITLE
Notification is not being shown 

### ISSUE THREAD

**Issue by thevpaliy** [googlesamples/android-UniversalMusicPlayer#164]
The issue occurs if you press the pause button (while playing a song) then you resume the playback by pressing it again(wait a few seconds) and then swipe the  app off the recent list. In this scenario a notification is never shown. However, if you just swipe the app off while playing a song (without pause/resume), it works as it supposed to. So it looks like that the notification appears only if the player hasn't previously been in a pause state, otherwise the entire thing shuts down.

This issue occurs on the Nexus 6P.

**Comment by nic0lette** [comment]
Given the rewrite, I'm not sure this would be occur any longer. If it does, please feel free to comment again.
