### ISSUE TITLE
All "getSupportMediaController()" cannot be resolved

### ISSUE THREAD

**Issue by SeekMyCosmic** [googlesamples/android-UniversalMusicPlayer#169]
All is OK, but "getSupportMediaController()" and "setSupportMediaController()" are red and cannot be resolved. 
I have updated dependencies as below:
`dependencies {
    provided 'com.google.android.wearable:wearable:2.0.5'

    compile 'com.google.android.gms:play-services-cast-framework:11.0.4'
    compile 'com.google.android.support:wearable:2.0.5'
    compile 'com.android.support:appcompat-v7:26.0.0'
    compile 'com.android.support:cardview-v7:26.0.0'
    compile 'com.android.support:mediarouter-v7:26.0.0'
    compile 'com.android.support:leanback-v17:26.0.0'
    compile 'com.android.support:design:26.0.0'

    compile 'com.google.android.exoplayer:exoplayer:r2.4.4'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support:support-annotations:26.0.0'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
}`
Please help me out! 
Thanks!

**Comment by SeekMyCosmic** [comment]
I have tried to recompile the source code without any change,  but I still met the problem as below: 
`Information:Gradle tasks [:mobile:generateDebugSources, :mobile:mockableAndroidJar, :mobile:prepareDebugUnitTestDependencies, :mobile:generateDebugAndroidTestSources]
Error:Execution failed for task ':mobile:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0) from [com.android.support:percent:26.0.0] AndroidManifest.xml:25:13-35
	is also present at [com.android.support:cardview-v7:25.4.0] AndroidManifest.xml:25:13-35 value=(25.4.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.
Information:BUILD FAILED
Information:Total time: 8.504 secs
Information:1 error
Information:0 warnings
Information:See complete output in console`

**Comment by cfva14** [comment]
Don't update the dependencies.
You are getting that error because  in the support libraries 26+ they have removed the getSupportMediaController and setSupportMeriaController


Or use the new methods. MediaController.getMediacontroller() and MediaController.setMediaController.

I don't remember if it is MediaControllerCompat.getMediaController() or MediaController.getMediaController().

Try both. I am in my cell phone.

**Comment by nic0lette** [comment]
As @cfva14 said, if you update the version of the support libraries to 26 (I'd recommend against that for the time being, unless you also want to update other parts of the code), then you'll need to change those to use ```MediaControllerCompat.setMediaController(Activity, MediaControllerCompat)``` and ```MediaControllerCompat.getMediaController(Activity)```.

[See MediaControllerCompat](https://developer.android.com/reference/android/support/v4/media/session/MediaControllerCompat.html).

**Comment by SeekMyCosmic** [comment]
It's great! Thanks for helping me out!
You are warmhearted and thank you again!

**Comment by SeekMyCosmic** [comment]
It's great! Thanks for helping me out!
You are warmhearted and thank you again!

**Comment by mr-shitou** [comment]
hi,this is a bug
v1/java

BaseActivity 
private void connectToSession(MediaSessionCompat.Token token) throws RemoteException {
        MediaControllerCompat mediaController = getSupportMediaController();
        if(mediaController == null) {
            mediaController = new MediaControllerCompat(this, token);
            setSupportMediaController(mediaController);

FullScreenPlayerActivity
     MediaControllerCompat mediaController = getSupportMediaController();

dependencies is 27.1.1
this problem maybe occured on merge ,please check project and I already know how to resolve this.
Thank you

**Comment by nic0lette** [comment]
This should be fixed by #249
