### ISSUE TITLE
Icon Fonts

### ISSUE THREAD

**Issue by Anatidae-Project** [googlesamples/android-UniversalMusicPlayer#17]
First, thanks for the code sample. Always love these. 

My "Issue" is that I'd like to see more of a movement from google in leveraging SVG or Icon Fonts. It strikes me as really wasteful to have 15 images for a play button when a single, crazy small, SVG would do.

**Comment by mangini** [comment]
Thanks for the suggestion, @Anatidae-Project . I took notes and will consider for a new version!
