### ISSUE TITLE
Data not cached on MediabrowserActivity Sleep

### ISSUE THREAD

**Issue by tosinamuda** [googlesamples/android-UniversalMusicPlayer#175]
The data doesnt get cached when the phone locks.
It makes request to the data source again

**Comment by nic0lette** [comment]
Hi,
You said, "It makes request to the data source again".
Do you mean it makes a network request for the JSON again, or do you mean it connects to the `MediaBrowserService` and `subscribe(...)` again?

**Comment by tosinamuda** [comment]
It calls onConnected again and unsubscribe then subscribe
