### ISSUE TITLE
Libararies compatibility issue

### ISSUE THREAD

**Issue by abdulwaheedandroid** [googlesamples/android-UniversalMusicPlayer#176]
I imported the project and I started getting error as mentioned below

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.0.0-alpha1, 25.2.0. 
Examples include `com.android.support:animated-vector-drawable:26.0.0-alpha1` and `com.android.support:percent:25.2.0`

below are my dependencies 

dependencies {
    provided 'com.google.android.wearable:wearable:2.0.3'

    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support:animated-vector-drawable:26.+'

    compile 'com.android.support:design:26.+'
    compile 'com.android.support:leanback-v17:26.+'
    compile 'com.android.support:cardview-v7:26.+'
    compile 'com.google.android.gms:play-services-cast-framework:11.0.1'
    compile 'com.google.android.exoplayer:exoplayer:r2.5.0'
    compile 'com.google.android.support:wearable:2.0.3'
    compile 'com.android.support:mediarouter-v7:26.+'
    compile 'com.google.android.gms:play-services-cast-framework:11.0.1'

    testCompile 'org.mockito:mockito-core:1.10.19'
    testCompile 'junit:junit:4.12'

    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    androidTestCompile 'com.android.support:support-annotations:26.+'
}
I googled and fixed with giving same library versions but still same error. If I try to compile the project it says getSupportMediaController Symbol not found. Am I missing anything?

**Comment by nic0lette** [comment]
Hi,
Sorry, but I'm not quite sure what you mean by "I imported the project", I don't think. The gradle files all call out specific version numbers (26.1.0, currently), so I'm not sure where the "26.+" version codes are from.

**Comment by RiccardoManoni** [comment]
Hi abdulwaheedandroid, I've had the same problem and solved it as suggested [here](https://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3/43110770) adding the code below in my app module build.gradle

`configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.4.0'
            }
       }
}`
