### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by darsimanoj** [googlesamples/android-UniversalMusicPlayer#178]
com/android/build/gradle/AppPlugin
 : Unsupported major.minor version 52.0

i runned gradlew build ,it downloaded something and said this above error

**Comment by dgaurav-163** [comment]
I am getting same error. Any one have idea, What I have to made change?

**Comment by darsimanoj** [comment]
yes ,first of all see the package name and create a new project with the package name as that package name.
and then copy the src  file to the newly created project files and replace the old files in it.
hope you have understood

**Comment by dgaurav-163** [comment]
Issue Fixed. I updated android studio and gradle version then same issue got fixed.

**Comment by darsimanoj** [comment]
ok
