### ISSUE TITLE
How to sort music file?

### ISSUE THREAD

**Issue by 11160920000144** [googlesamples/android-UniversalMusicPlayer#188]
Hello, I've used my own json file...
and I've used a tracknumber sorted from 1 to 100...
but the music showed randomly... is it right to sort from json file tracknumber?
or is there any source code that I've to change? please help me... I'm trying to add aroun 200 music, but it sorted randomly...

**Comment by nic0lette** [comment]
Hi,
Sorry about the confusion. UAMP actually doesn't sort the titles at all currently, and (I think) simply returns titles based on the ordering of the iterator of a `ConcurrentMap` (which isn't very orderly).

I would suggest updating `com.example.android.uamp.model. MusicProvider.buildListsByGenre()` to sort the lists after, or as, they're being built based on your criteria.

https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L250

Sorry it's a bit complicated at the moment.

**Comment by 11160920000144** [comment]
hello, thx for your reply...
buildListsByGenre() is sorted by .METADATA_KEY_GENRE where it used string data type
now, I'm trying  to sort using .METADATA_KEY_TRACK_NUMBER but it used long data type
I use the code like this
`    private synchronized void buildListsByGenre() {
        ConcurrentMap<Long, List<MediaMetadataCompat>> newMusicListByGenre = new ConcurrentHashMap<>();

        for (MutableMediaMetadata m : mMusicListById.values()) {
            Long number = m.metadata.getLong(MediaMetadataCompat.METADATA_KEY_TRACK_NUMBER);
            List<MediaMetadataCompat> list = newMusicListByGenre.get(number);
            if (list == null) {
                list = new ArrayList<>();
                newMusicListByGenre.put(number, list);
            }
            list.add(m.metadata);
        }
        mMusicListByGenre = newMusicListByGenre;
    }`
an it says error in here
mMusicListByGenre = newMusicListByGenre; ->
Incompatible types.
Required:
ConcurrentMap
<java.lang.String,
List<MediaMetadataCompat>>
Found:
ConcurrentMap
<java.lang.Long,
List<MediaMetadataCompat>>

Can you help me what should I change for sorting by tracknumber?
because I'm still a student and I'm very newbie in this.
thx

**Comment by nic0lette** [comment]
Something like this:

```    private synchronized void buildListsByGenre() {
        ConcurrentMap<String, List<MediaMetadataCompat>> newMusicListByGenre = new ConcurrentHashMap<>();

        for (MutableMediaMetadata m : mMusicListById.values()) {
            String genre = m.metadata.getString(MediaMetadataCompat.METADATA_KEY_GENRE);
            List<MediaMetadataCompat> list = newMusicListByGenre.get(genre);
            if (list == null) {
                list = new ArrayList<>();
                newMusicListByGenre.put(genre, list);
            }
            list.add(m.metadata);
            Collections.sort(list, new Comparator<MediaMetadataCompat>() {
                @Override
                public int compare(MediaMetadataCompat left, MediaMetadataCompat right) {
                    final long leftTrack = left.getLong(MediaMetadataCompat.METADATA_KEY_TRACK_NUMBER);
                    final long rightTrack = right.getLong(MediaMetadataCompat.METADATA_KEY_TRACK_NUMBER);
                    return (leftTrack < rightTrack) ? -1 : (leftTrack == rightTrack ? 0 : 1);
                }
            });
        }
        mMusicListByGenre = newMusicListByGenre;
    }```

**Comment by 11160920000144** [comment]
thanks so much... it's perfectly working... you save my day...
