### ISSUE TITLE
Searchview not working

### ISSUE THREAD

**Issue by arushk1** [googlesamples/android-UniversalMusicPlayer#19]
I added a searchview item to main.xml (menu). And inflated it from MusicPlayerActivity from onCreateOptions. The icon is there but the text view won't show up.

Thanks!

**Comment by mangini** [comment]
This is not a place for questions on your code. If you have an __issue__ with UniversalMusicPlayer, post it here. If you have generic questions or questions on your modifications of UniversalMusicPlayer, please use StackOverflow.
