### ISSUE TITLE
Failed to resolve: com.android.support:support-core-utils:25.4.0

### ISSUE THREAD

**Issue by a442509097** [googlesamples/android-UniversalMusicPlayer#190]
Failed to resolve: com.android.support:support-core-utils:25.4.0
Failed to resolve: com.android.support:support-annotations:25.4.0
and build so slow; use 3.3 Gradle, Android Studio 3.0.1

**Comment by a442509097** [comment]
Ok, Solve this.
step 1: download and extract "mobile" folder.
step 2: new project and delete "MainActivity ", "activity_main.xml".
step 3: copy  "mobile" folder overwrite for all to new project(root folder).
then , will working fine.

**Comment by nic0lette** [comment]
When/how does this happen? When you fork this project or when importing this as a code sample?
Why are you using support lib 25.4.0?
