### ISSUE TITLE
when I run this project in my AS，there is nothing?no music,no place to play

### ISSUE THREAD

**Issue by JM0425** [googlesamples/android-UniversalMusicPlayer#192]
just like this image
![_20171219095503](https://user-images.githubusercontent.com/9896507/34136939-27ac8378-e4a3-11e7-9fbb-d3d0f0983758.png)

**Comment by nic0lette** [comment]
Does this link work for you: [https://storage.googleapis.com/automotive-media/music.json](https://storage.googleapis.com/automotive-media/music.json)?

**Comment by nic0lette** [comment]
If you continue to experience problems, despite being able to access the above URL, please let me know and I can reopen this issue.
