### ISSUE TITLE
Crashes when scrolling over a large number of items on the listview

### ISSUE THREAD

**Issue by ryanckim** [googlesamples/android-UniversalMusicPlayer#195]
I haven't been able to confirm this with the un-modified playlists because they were not long enough. But what I have tested just now is 

1) Run a web server on my android device to serve the music files and the json file (all properly formatted and located)
2) Modify the RemoteJSONSource.java code so that the CATALOG_URL points to my own internal json file

So when I now run the app it reads and plays fine from my internal web server and json etc. But now I have much more items displayed on the screen so I need to scroll to browse through the list. 

And when I scroll up and down for a little while, the app always crashes. And then, especially when I am streaming to Chromecast Audio, the connection is lost although the cast icon still remains as I re-open the app.

I've googled this problem and noticed that this may be related to memory leak or something, but haven't been able to find a straightforward solution. Any help / info would be appreciated.

And lastly, as a suggestion, I think it would be nice if the listview can automatically follow the currently playing item (when that is out of the current view). So for example, when I play the last item on the listview screen, as the next song starts the listview would scroll automatically by one line so that the next item is shown as playing (in addition to the one with the controls at the bottom).

**Comment by nic0lette** [comment]
Do you have a stack trace for the crash? Or is it an ANR?

The current design doesn't handle a large catalog out of the box, unfortunately. It would be best to, if you need to have a lot of items, that you use pagination with [void subscribe (String parentId, Bundle options, MediaBrowserCompat.SubscriptionCallback callback)](https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat.html#subscribe%28java.lang.String, android.os.Bundle, android.support.v4.media.MediaBrowserCompat.SubscriptionCallback%29) with [EXTRA_PAGE](https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat.html#EXTRA_PAGE) and [EXTRA_PAGE_SIZE](https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat.html#EXTRA_PAGE_SIZE).

**Comment by kimerahan** [comment]
its most likely memory issue

**Comment by nic0lette** [comment]
It's not recommended to send so many items at once. Using the extras I described above is the recommended way for now. In the future, looking at [MediaBrowser2.getChildren](https://developer.android.com/reference/androidx/media/MediaBrowser2.html#getChildren%28java.lang.String%2C%2520int%2C%2520int%2C%2520android.os.Bundle%29) might work well for you.
