### ISSUE TITLE
MediaControllerCompat.Callback never called  at background

### ISSUE THREAD

**Issue by Yourbadman** [googlesamples/android-UniversalMusicPlayer#196]
App background , but  MediaControllerCompat.Callbck　nerver called when playback state change?

**Comment by nic0lette** [comment]
The app unregisters the callback in `onStop`.

MediaNotificationManager also has a callback registered, and that one does get triggered while the app is in the background.

**Comment by Yourbadman** [comment]
MeidaControllerCompat.registerCallback(callback,Handler),  handler must has main looper.
