### ISSUE TITLE
how can we store the internal and external songs of the device

### ISSUE THREAD

**Issue by JineshS** [googlesamples/android-UniversalMusicPlayer#197]
Hello sir/mam,

Please tell me  that how can we displaythe internal and external songs of the device in listview.

**Comment by nic0lette** [comment]
This is a complex change that would require a lot of changes to the code.

You can see the basic code to get the music on a device here: [MusicRetriever.java](https://android.googlesource.com/platform/development/+/master/samples/RandomMusicPlayer/src/com/example/android/musicplayer/MusicRetriever.java)

The app isn't currently structured for handling a lot of music, however, so after importing music into MusicService, you'll probably want to request the media using pages with this method: https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat.html#subscribe(java.lang.String, android.os.Bundle, android.support.v4.media.MediaBrowserCompat.SubscriptionCallback)

Sorry that I won't be able to help you more with this, but if you have more questions I'd recommend posting them to [StackOverflow](https://stackoverflow.com).
