### ISSUE TITLE
How to get duration if can not get from server ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googlesamples/android-UniversalMusicPlayer#198]
I have music files on server but i don't have duration for each music how to update duration if i don't have duration from server ?

**Comment by nic0lette** [comment]
The easiest is to get the duration and add it to the JSON that's being returned. (If you're using another method to get the list of songs then this may not be good advice any longer.)

If you can wait until the song begins, then you can use [getDuration()](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html#getDuration--) from the SimpleExoPlayer in [LocalPlayback](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/playback/LocalPlayback.java).

**Comment by mnk98** [comment]
How we can get duration with new structure, there is no LocalPlayback.
