### ISSUE TITLE
VoiceSearch not working

### ISSUE THREAD

**Issue by arushk1** [googlesamples/android-UniversalMusicPlayer#20]
So far, the voice search is only working with one Artist (Play <artists_name>). Any other Play query doesn't work. How to fix that?

**Comment by mangini** [comment]
Can you provide a better description? Which search is working and which is not working?

**Comment by arushk1** [comment]
I say the command "Play Antariksh", antariksh being the artist name, that's working. Any other command doesn't work. That happened to be the first command that I said and it worked. So far no other play command works. Except of course the "Play Music" in which case Google Play Music starts.

**Comment by mangini** [comment]
How "Play Antariksh" worked if there is no artist "Antariksh" on this app's library? Can you test with Universal Music Player and report your results? For every issue you report, please provide:
- what EXACTLY doesn't work with an unmodified version of Universal Music Player;
- where are you searching from? Do you say "Ok, Google" on the main Android screen and follow up with a search?
- what are the versions of your android build and Google Play Services?
- look at adb logcat and copy the relevant parts immediately after you issue a voice search that doesn't work. Make sure you don't paste any personal data here.

**Comment by mangini** [comment]
Closing because of the lack of information. Please, reopen if you get more data.
