### ISSUE TITLE
Error in this project

### ISSUE THREAD

**Issue by jobandeep** [googlesamples/android-UniversalMusicPlayer#200]
![screenshot 242](https://user-images.githubusercontent.com/36124991/35775657-ea440954-09b2-11e8-8d24-5e3f7563870d.png)
Hey!

I found an error in this project. When I have started this work using Mobile API and Android auto and Android Wear, I think it is only for Android Mobile and Tablets.  Tell me, please. Via my mail joban3167@gmail.com Also I share the screenshot which I found an error. 
![screenshot 242](https://user-images.githubusercontent.com/36124991/35775651-def6bace-09b2-11e8-99b6-d113d41c96c1.png)

Thanks
Joban

**Comment by nic0lette** [comment]
Hi Joban,
Could you explain in more detail what you mean by "found an error in this project"? The screenshots you posted look like the dependencies on Google Play Services didn't get pulled in correctly.

**Comment by jobandeep** [comment]
I am putting all dependencies which listed in build.gradle. After putting all the code and then try to clean project then it shows me an error in this project. Let me know how could be solved this coding. Otherwise, send your created project to me.

**Comment by nic0lette** [comment]
If you just clone this repo and try to build it, without making any chances, does it work?
