### ISSUE TITLE
Android Auto app does not recognize it

### ISSUE THREAD

**Issue by MoshePupkin** [googlesamples/android-UniversalMusicPlayer#201]
So I've cloned, compiled and installed the project. Android Auto app does not recognize it. Other apps do work with it.

Any idea what's wrong?

**Comment by nic0lette** [comment]
You've [tried this](https://productforums.google.com/forum/#!topic/android-auto/KGD_WqILlrY;context-place=forum/android-auto) and it doesn't work?

**Comment by MoshePupkin** [comment]
How is this related to my question?

**Comment by nic0lette** [comment]
Sorry, that was the wrong link =/
[Testing Apps for Auto](https://developer.android.com/training/auto/testing/index.html#phone)

Basically you need to enable unknown sources in the Android Auto companion app otherwise only approved apps will show up.

**Comment by nic0lette** [comment]
I'll close this for now, but please reply or open a new issue if there's more.
