### ISSUE TITLE
How do i change the size of the audio control bar or make it transparent when using android auto?

### ISSUE THREAD

**Issue by ravir0611** [googlesamples/android-UniversalMusicPlayer#203]
![capture](https://user-images.githubusercontent.com/37084592/36995255-30815b88-2079-11e8-92d6-390132cf354f.PNG)

**Comment by nic0lette** [comment]
Hi @ravir0611! Sorry, but the UI is controlled by Android Auto, and so there's not much customization that's possible. You can read more about what *is* possible here: [Designing for Auto](https://developer.android.com/design/auto/index.html).

**Comment by ravir0611** [comment]
Thank you.
