### ISSUE TITLE
sorting music list

### ISSUE THREAD

**Issue by kimerahan** [googlesamples/android-UniversalMusicPlayer#206]
in the MusicProvider
public Iterable<MediaMetadataCompat> getShuffledMusic() {
        if (mCurrentState != State.INITIALIZED) {
            return Collections.emptyList();
        }
        List<MediaMetadataCompat> shuffled = new ArrayList<>(mMusicListById.size());
        for (MutableMediaMetadata mutableMetadata : mMusicListById.values()) {
            shuffled.add(mutableMetadata.metadata);
        }
        
        Collections.shuffle(shuffled);
        return shuffled;
    }

in the QueueHelper class
public static List<MediaSessionCompat.QueueItem> getRandomQueue(MusicProvider musicProvider) {
        List<MediaMetadataCompat> result = new ArrayList<>();//RANDOM_QUEUE_SIZE
        Iterable<MediaMetadataCompat> shuffled = musicProvider.getShuffledMusic();
        for (MediaMetadataCompat metadata : shuffled) {
           /* if (result.size() == RANDOM_QUEUE_SIZE) {
                break;
            }*/
            result.add(metadata);
        }
        LogHelper.d(TAG, "getRandomQueue: result.size=", result.size());

        return convertToQueue(result, MEDIA_ID_MUSICS_BY_SEARCH, "random");
    }

**Comment by nic0lette** [comment]
I wasn't exactly sure I understood, but using the Kotlin version it shouldn't be too difficult to sort the items returned returned from the media server.

The code that builds the BrowseTree is in [BrowseTree.kt](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/fc569696dd5dcaf7a8e1fa6bdeea82b30cf5f9d9/media/src/main/java/com/example/android/uamp/media/library/BrowseTree.kt#L65-L69), and it should be possible to either change the constructor to sort in any way that you'd like, or add a new method to return the items in another order, if you'd like.
