### ISSUE TITLE
Add new fuction

### ISSUE THREAD

**Issue by wangzhifengharrison** [googlesamples/android-UniversalMusicPlayer#207]
If I want to add some new function on the APP. The APP is a prototype design, and I want to add some new function on this APP. What I should do. Thanks.

**Comment by wangzhifengharrison** [comment]
Yes, I have completed a login part which is new function in this APP. We can use the login system to store music in the APP for future software development. I will test this part, if this part work well in my computer, I will create a pull request. Cheers.

**Comment by nic0lette** [comment]
That sounds fine to me. Open a PR if you decide to contribute your changes back to the project.

I'll close this issue since it doesn't seem to actually be an issue. :)
