### ISSUE TITLE
Handling config changes

### ISSUE THREAD

**Issue by ingsaurabh** [googlesamples/android-UniversalMusicPlayer#217]
I am trying uamp sample, whenever orientation changes MediaBrowserFragment recyclerview state is lost(its scroll position is not maintained).

My problem is how to maintain scroll position in uamp sample.

I know I can save scroll position and restore it later but since recyclerView itself maintains scroll state I don't want that hacks.

I tried pushing this simple fragment instead of MediaBrowserFragment and its maintaining its scroll

```
public class TestFragment extends Fragment {

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View mRootView = inflater.inflate(R.layout.fragment_test, container, false);
        RecyclerView recyclerView = (RecyclerView) mRootView.findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        recyclerView.setAdapter(new RecAdapter());
        return mRootView;
    }


    private class RecAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

        @NonNull
        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.layout_text, null);
            return new ItemViewHolder(itemView);
        }

        @Override
        public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
            ((ItemViewHolder) holder).title.setText(""+ position);
        }

        @Override
        public int getItemCount() {
            return 200;
        }
    }

    private class ItemViewHolder extends RecyclerView.ViewHolder {
        TextView title;

        ItemViewHolder(View itemLayoutView) {
            super(itemLayoutView);
            title = (TextView) itemLayoutView.findViewById(R.id.title);
        }
    }
}
```

**Comment by nic0lette** [comment]
This should be better in the rewrite, but there might be some work to do, which would require more work than is probably appropriate for this sample.

If you disagree and want to create a PR to address this I'd be more than happy to review and include it.

**Comment by ingsaurabh** [comment]
Can you please provide more inputs in this case, how should I proceed, will be happy to contribute on this matter.

**Comment by nic0lette** [comment]
I'm not sure. I use the app with the default catalog, which isn't many songs, so it doesn't create a problem for me. :)

**Comment by ingsaurabh** [comment]
Then in this case, please reopen the issue, as If this is not a problem for you doesn't  mean the problem doesn't exists :) , also not everyone is using the default catalog of 10 or 12 songs.
