### ISSUE TITLE
Issue regarding load music

### ISSUE THREAD

**Issue by mohsin111** [googlesamples/android-UniversalMusicPlayer#22]
java.lang.RuntimeException: Unable to create service com.example.android.uamp.MusicService: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.addVideoCastConsumer(com.google.android.libraries.cast.companionlibrary.cast.callbacks.VideoCastConsumer)' on a null object reference

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.addVideoCastConsumer(com.google.android.libraries.cast.companionlibrary.cast.callbacks.VideoCastConsumer)' on a null object reference

**Comment by mangini** [comment]
Can you provide more information? Specifically, a full stack trace (with lines of code), what where you doing when this exception was raised and if this is reproducible or it's a one-off?

**Comment by mohsin111** [comment]
actually it works fine now.I have comment the code.so not work.but right now it works perfect.thank you!
