### ISSUE TITLE
Bug pressing play after notification dismissed

### ISSUE THREAD

**Issue by sebaslogen** [googlesamples/android-UniversalMusicPlayer#231]
**Reproduction scenario**:
- Open the app
- Open "Irsen's Tale" playlist
- Play "Intro"
- press pause
- Press home
- Swipe notification away
- Bring app back from recent apps menu
- Press play on the same "Intro" element (it now has a play button icon)

**Outcome**: Nothing happens (play only works on other tracks)

**Expected**: After press the "Intro" track starts playing

**Test device**: Pixel 2
**Version of the app**: Commit 9fe7368361f2c3df77a019953d2bdbb660b73d2b

**Comment by nic0lette** [comment]
This should be working. Let me know if you see it happening again :) Thanks for your report!
