### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [googlesamples/android-UniversalMusicPlayer#232]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, your logo on this project so generic and unatractive. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by nic0lette** [comment]
If you'd like to create something and open a PR then I'd certainly be open to (and grateful for) that. I will warn you ahead of time that while the icon is rather generic, I suppose I am a bit picky about the icon nevertheless. :)

If you'd still like to do this, then please take a look at [this post](https://medium.com/google-design/designing-adaptive-icons-515af294c783) by Nick Butcher about designing adaptive icons, and be sure to create vector assets :)

Just let me know what you'd like to do.

But thank you either way for reaching out!
