### ISSUE TITLE
How to implement shuffle and repeatmode functionality with this example

### ISSUE THREAD

**Issue by kanivel** [googlesamples/android-UniversalMusicPlayer#236]
Hi,

      How do you get exoplayer object from service to set repeatmode and shuffle functionality.

**Comment by nic0lette** [comment]
You don't. You use the transport controls to do it. For example: `transportControls.setRepeatMode(PlaybackStateCompat.REPEAT_MODE_ALL)`

If you use [this project](https://github.com/googlesamples/android-media-controller), you can see how that works.

**Comment by KulwinderSinghRahal** [comment]
Do ExoPlayer automatically handles `repeatMode` and `shuffleMode` with help of `MediaSessionConnector` ?

**Comment by nic0lette** [comment]
Yes it does. It's passed through the `MediaSessionConnector` and handled by the class [`DefaultPlaybackController`](https://github.com/google/ExoPlayer/blob/1c6149b4d71c2948b1d8212783a5423fcdae079b/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/DefaultPlaybackController.java#L134). There it just sets `Player.setRepeatMode` and `Player.setShuffleModeEnabled` respectively. (So it depends on setting up a `Timeline` in ExoPlayer.)

**Comment by KulwinderSinghRahal** [comment]
Then how UI will be updated , ie. how i can show Currently Shuffle mode is enabled or disabled ?
