### ISSUE TITLE
有没有java的demo?

### ISSUE THREAD

**Issue by qq2748** [googlesamples/android-UniversalMusicPlayer#237]

**Comment by qq2748** [comment]
现在是kotlin的代码  看不懂

**Comment by HanderWei** [comment]
v1 branch

And don't use Chinese, please.

**Comment by qq2748** [comment]
sorry , i just ask Chinese people .

**Comment by qq2748** [comment]
sorry,  i just ask chinese people for help before, i dont think too more,  sorry, because i think this question too fool, and my english too bad!

**Comment by jellybean13** [comment]
You can switch the branch to "next". Only "master" branch use Kotlin.

**Comment by nic0lette** [comment]
Sorry. Yes, the Java code is in the "v1" branch.

抱歉。 是的，Java代码在[「v1」](https://github.com/googlesamples/android-UniversalMusicPlayer/tree/v1)中。

**Comment by qq2748** [comment]
thank you so much
