### ISSUE TITLE
make it podcast like app?

### ISSUE THREAD

**Issue by jimlee2** [googlesamples/android-UniversalMusicPlayer#24]
I want to create an audio book which the app plays songs from my server 
so every week I can upload a new podcast on server and it can be played in the app

I am not sure how to make the app so it can get the songs from my serer
really appreciate any help
thanks

**Comment by mangini** [comment]
This is not the best place to post requests like this. A discussion forum is more appropriate. If you have an issue (ie, a bug) on UniversalMusicPlayer, this is the right place.
