### ISSUE TITLE
MediaMetadataCompat.fullDescription fails if extras is null

### ISSUE THREAD

**Issue by jasonostrander** [googlesamples/android-UniversalMusicPlayer#240]
The current code:
```
inline val MediaMetadataCompat.fullDescription
    get() =
        description.also {
            it.extras?.putAll(bundle)
        }
```
If description.extras is null, then this code is a no-op and just returns the existing description. 

Diving into MediaMetadataCompat source, I see that the extras field is only populated if the existing bundle contains either METADATA_KEY_BT_FOLDER_TYPE or METADATA_KEY_DOWNLOAD_STATUS. If neither of those is present, then the extras will be null by default.

**Comment by nic0lette** [comment]
That's why [this code](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/media/src/main/java/com/example/android/uamp/media/library/JsonSource.kt#L159) is there:

```
    // Add downloadStatus to force the creation of an "extras" bundle in the resulting
    // MediaMetadataCompat object. This is needed to send accurate metadata to the
    // media session during updates.
    downloadStatus = STATUS_NOT_DOWNLOADED
```

**Comment by jasonostrander** [comment]
Ah, thank you! I was not aware of that. Closing.
