### ISSUE TITLE
 Scavenging the background program when Music is playing

### ISSUE THREAD

**Issue by MoreToMore** [googlesamples/android-UniversalMusicPlayer#241]
I cloned the V1 branch and I clean up the background program While UniversalMusicPlayer is running,then the UniversalMusicPlayer Stops running. What should I do to Keep UniversalMusicPlayer running.Can you help me, Thank you!

**Comment by nic0lette** [comment]
In order to keep playing music after swiping away the task from the recents list, [remove this function](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/3dc0769fb3cc4b4faaae48b6f85e754df5a60ece/mobile/src/main/java/com/example/android/uamp/MusicService.java#L277)

```
public void onTaskRemoved(Intent rootIntent) {
    super.onTaskRemoved(rootIntent);
    stopSelf();
}
```

**Comment by MoreToMore** [comment]
thank you
