### ISSUE TITLE
MediaSessionCompat not working properly

### ISSUE THREAD

**Issue by dharmeshRughani1234** [googlesamples/android-UniversalMusicPlayer#242]
![device-2018-08-07-194132](https://user-images.githubusercontent.com/29123662/43782323-b9994b9c-9a7c-11e8-8b55-a989f5edbb4a.png)

Hello , In this code we only able to pause the media state in lock screen widget , what i want is i want to remove this widget on destroy of service , any suggestion , have attached a screenshot for better understand . have tried a lot by releasing the media session but can't be succeed .

**Comment by nic0lette** [comment]
That widget is generated from the notification, so to remove it, you'd want to cancel the notification.
