### ISSUE TITLE
UniversalMusicPlayer latest code in Java

### ISSUE THREAD

**Issue by vicgithb** [googlesamples/android-UniversalMusicPlayer#243]
Are there any near future plans to provide UniversalMusicPlayer codebase in Java as well (Implemented using Architecture components)? 

Most of the development work that involves Architecture components is available in Kotlin only. Conversion of java project to kotlin is supported by Android Studio. To learn new Android features one have to learn kotlin first.

**Comment by nic0lette** [comment]
Sorry, but there aren't any plans at the moment for this.

Yes, Android Studio has a conversion tool from Java to Kotlin, but the code is not always quite as idiomatic and often benefits from updating, so it's not quite as easy as having a Java version and running the conversion to generate a Kotlin version.

But yes, development of UAMP is going to remain focused on Kotlin and there are, unfortunately, no current plans to provide a parallel version in Java.
