### ISSUE TITLE
How to make the MusicService to be a remote process

### ISSUE THREAD

**Issue by callmekendy** [googlesamples/android-UniversalMusicPlayer#247]
I Found if I set the MusicService to be a remote process, MediaBrowserCompat.SubscriptionCallback.onError() will be called.  So, how to make it works? Thanks.

**Comment by nic0lette** [comment]
Can you try again with the code that's in master? When I move `MusicService` to another process it works fine as far as I can see.

```
<service
    android:name=".MusicService"
    android:process=":service"
    android:enabled="true"
    android:exported="true"
    tools:ignore="ExportedService">

    <intent-filter>
        <action android:name="android.media.browse.MediaBrowserService" />
    </intent-filter>
</service>
```

**Comment by callmekendy** [comment]
It works, Thank you.

> Can you try again with the code that's in master? When I move MusicService to another process it works fine as far as I can see.
