### ISSUE TITLE
while opening without internet it shows " Unfortunately, UAMP has stopped" 

### ISSUE THREAD

**Issue by mriax** [googlesamples/android-UniversalMusicPlayer#254]
have an issue when i switched Off the Wifi it shows "Unfortunately, UAMP has stopped" while opening in offline mode.
otherwise its fine.

Help me out, that would be appreciable.

**Comment by febimfelix** [comment]
Add an Internet connection check in JsonSource.kt before starting UpdateCatalogTask.

**Comment by nic0lette** [comment]
This should be fixed with the [latest push](https://github.com/googlesamples/android-UniversalMusicPlayer/commit/47da058112cee0b70442bcd0370c1e46e830c66b).
