### ISSUE TITLE
How to run this palyer on android  watch os emulator

### ISSUE THREAD

**Issue by we10710aa** [googlesamples/android-UniversalMusicPlayer#280]
This might be a stupid question, I got a little bit confused, can I run this app on Watch OS? If it can, how to do that? I tried to run it on watch os emulator but an error showed up:
> missing uses-feature watch, non watch apk can not be launched on a watch.

**Comment by nic0lette** [comment]
Sorry, UAMP doesn't currently run on a WearOS device, but if it's running on an Android phone, you should be able to interact with it via your Wear OS device.

#224 was opened to support running the app directly on WearOS.
