### ISSUE TITLE
Support Play X with Y voice action

### ISSUE THREAD

**Issue by keithsmyth** [googlesamples/android-UniversalMusicPlayer#297]
Handle android.media.action.MEDIA_PLAY_FROM_SEARCH intent to allow 'Play X on Y' voice commands (requirement for Android Auto).

https://developer.android.com/guide/components/intents-common#PlaySearch

**Comment by nic0lette** [comment]
This should already be supported.

**Comment by keithsmyth** [comment]
None of the manifests support this intent yet, and it is still a requirement to do so for supporting Android Auto
