### ISSUE TITLE
Bug: clicking the notification sometimes doesn't do anything

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-UniversalMusicPlayer#3]
I have no idea what has caused it, but I've played a bit with the app, and on the first few moments it worked fine, yet now when I click the notification it doesn't open the app.

**Comment by mangini** [comment]
Thanks for reporting. Can you reproduce it by killing the app process and finding a set of actions that recreate the issue?

**Comment by AndroidDeveloperLB** [comment]
@mangini I've now tried to play a bit with the app and couldn't reproduce it.
I didn't expect to see it happens when I played with it before.
The only thing I remember doing is:
open app, play 2 songs from the "rock" category. exit the app (stop playing before). start again with a song in the "cinematic" category, play next within the app, go to background (or press back?) and then try to click the notification when it's in expanded mode.

I might be wrong with some of those steps, which might be why I can't reproduce it.
If it helps, my device is I9300 with CM12 (Android 5.0.2) .

**Comment by mangini** [comment]
Thank you, @AndroidDeveloperLB . I will leave the bug open for a while in case we find a reliable repro.

**Comment by AndroidDeveloperLB** [comment]
@mangini Thank you for this nice sample. Can you please post samples of the built in apps of Android? I know most are already open source, but none exist as a "portable" version like this one. I'm talking about those apps: Launcher, contacts/dialer, Gallery ,...

**Comment by mangini** [comment]
Closing this as we couldn't repro it. Please open a new issue if you are able to reproduce the bug.

**Comment by AndroidDeveloperLB** [comment]
@mangini OK. Maybe it was a bug on the OS itself, as I use CM .
