### ISSUE TITLE
Notification.MediaStyle move about restlessly when GooglePlayMusic is pausing

### ISSUE THREAD

**Issue by night1231** [googlesamples/android-UniversalMusicPlayer#31]
About this app, Notification.MediaStyle move up and down if I push the fastforward button when there is GooglePlayMusic's Notification.

How can I fix it?

**Comment by mangini** [comment]
That is a consequence of a bug on notification ranking in Lollipop when there are two active MediaSessions. It is fixed in Marshmallow. I'm not aware of a workaround, unfortunately.
