### ISSUE TITLE
Music Service is stopped on removing app from recent apps - Only after playing a second media

### ISSUE THREAD

**Issue by smabbas1234** [googlesamples/android-UniversalMusicPlayer#34]
Music Service is stopped on removing app from recent apps.

This doesn't happen when playing first media/song, But after playing any other media/song after that, the service no longer runs independently. It stops on removing app from recent apps.

**Comment by saikiranpsq** [comment]
Even i'm facing the same problem, waiting for the solution.

**Comment by Hackmodford** [comment]
Same here

**Comment by Hackmodford** [comment]
Figured it out in my app. Keep an eye out for mService.stop(true)

**Comment by nic0lette** [comment]
UAMP now stops playback, intentionally, when it's dismissed from the recent apps list.
