### ISSUE TITLE
Add album cover in the MediaItemViewHolder

### ISSUE THREAD

**Issue by rainman20** [googlesamples/android-UniversalMusicPlayer#37]
* I know most questions not related to the bug dont get any answer here, but the problem with asking questions about ump in Stackoverflow is that not many people take time to go over the project to answer a question - you guys know everything and really appreciate if help me with this. 

I want to access album cover in the `MediaItemViewHolder.java` instead of the play icons. I followed [this pattern from PlaybackControlsFragment.java](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/b729def3679cac2d66136e8fdc9237d01bfb485c/mobile/src/main/java/com/example/android/uamp/ui/PlaybackControlsFragment.java#L148) and added this: 
```
String artUrl = description.getIconUri().toString();
Bitmap art = description.getIconBitmap();
AlbumArtCache cache = AlbumArtCache.getInstance();
 if (art == null) {
   art = cache.getIconImage(artUrl);
}
if (art != null) {
   holder.mImageView.setImageBitmap(art);
}
```
and added this to the cases 
```
holder.mImageView.setImageBitmap(art);
```

it correctly shows the album art, however, the image is blank until I click the item. Then the album cover is loaded and displayed. I think it has something to do with `AlbumArtCache`. 

Is it possible to display the album covers without waiting for the user to click on an item?

note: I have asked this question in [stackoverflow](http://stackoverflow.com/questions/31756883/android-universal-music-player-add-album-cover-in-the-mediaitemviewholder) too

**Comment by nageshs** [comment]
Answered on stackoverflow

**Comment by avluis** [comment]
@rainman20 How did you manage to solve this - I have yet to crack it.
Care to share?

**Comment by rainman20** [comment]
@avluis please check nageshs answer on Stackoverflow

**Comment by avluis** [comment]
@rainman20 I did, but I may not be doing something right - I can see Bitmap complain about my uri's as I try to load them in - so stumped, lol.
