### ISSUE TITLE
Networking on Main Thread

### ISSUE THREAD

**Issue by joachim-g** [googlesamples/android-UniversalMusicPlayer#39]
Hi,

while looking through this very nice example, I found that it's performing networking on the Main Thread in MusicProvider#fetchJSONFromUrl.
Are you sure that's recommended best practice? Especially in a sample app provided by Google?

Just my $0.02
;)

**Comment by nageshs** [comment]
`fetchJSONFromUrl(..)` is only ever called from `retrieveMedia()` which itself is only ever called from within an `AsyncTask`. Do you see it being called on the main thread? If so can you please provide a stacktrace

**Comment by joachim-g** [comment]
you're right, didn't see that. 
my bad, sorry :/
