### ISSUE TITLE
Request: MediaPlayer Proxy or Cache

### ISSUE THREAD

**Issue by avluis** [googlesamples/android-UniversalMusicPlayer#41]
While I believe this may not fit entirely with the purpose of UniversalMusicPlayer - I do believe it fits within the aspects of a streaming Media Player.
The few samples available online on how to approach a proxy implementations date back to the [NPR app](https://code.google.com/p/npr-android-app/) but it hasn't aged well.

So, as titled, I am requesting for UniversalMediaPlayer to be enhanced with a proxy service for the media player to use as a cache.

**Comment by mangini** [comment]
Thanks for the suggestion, but it is really not in the scope of uAmp for the next versions. I will take notes for a future version, though.
