### ISSUE TITLE
Connect with wearable and TV

### ISSUE THREAD

**Issue by AshishPsaini** [googlesamples/android-UniversalMusicPlayer#42]
How can we connect it with wearable and TV . Please provide the suggestion

**Comment by mangini** [comment]
- Wearable: when playing a music on the phone, you will be able to control it from the watch (Android Wear);
- TV: It has an Android TV UI, which means you can install it on your Android TV directly;
- TV (Cast): It supports Google Cast. Use a network where there's a Cast device around you and you will see the Cast icon on the ActionBar.
