### ISSUE TITLE
Inconsistent state of genre Map

### ISSUE THREAD

**Issue by gonzalomelov** [googlesamples/android-UniversalMusicPlayer#45]
In the MusicService, after the bitmap is fetched, the MediaMetadata *track* is assigned to another newly created MediaMetadata instance, and then the MusicProvider method, updateMusic, is called with this new instance.

In this method, the metadata of the MutableMediaMetadata track, in the mMusicListById map, is updated to the new instance. So, if the genre hasn't been changed, and therefore, the genre map not updated, it's still pointing to the old instance of the MediaMetadata track.

MusicService.java
-----------------

    ...

    AlbumArtCache.getInstance().fetch(albumUri, new AlbumArtCache.FetchListener() {
        @Override
        public void onFetched(String artUrl, Bitmap bitmap, Bitmap icon) {
            MediaSession.QueueItem queueItem = mPlayingQueue.get(mCurrentIndexOnQueue);
            MediaMetadata track = mMusicProvider.getMusic(trackId);
            track = new MediaMetadata.Builder(track)

                // set high resolution bitmap in METADATA_KEY_ALBUM_ART. This is used, for
                // example, on the lockscreen background when the media session is active.
                .putBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART, bitmap)

                // set small version of the album art in the DISPLAY_ICON. This is used on
                // the MediaDescription and thus it should be small to be serialized if
                // necessary..
                .putBitmap(MediaMetadata.METADATA_KEY_DISPLAY_ICON, icon)

                .build();

            mMusicProvider.updateMusic(trackId, track);

            // If we are still playing the same music
            String currentPlayingId = MediaIDHelper.extractMusicIDFromMediaID(
                queueItem.getDescription().getMediaId());
            if (trackId.equals(currentPlayingId)) {
                mSession.setMetadata(track);
            }
        }
    });
    ...

MusicProvider.java
------------------

    ...
    public synchronized void updateMusic(String musicId, MediaMetadata metadata) {
        MutableMediaMetadata track = mMusicListById.get(musicId);
        if (track == null) {
            return;
        }

        String oldGenre = track.metadata.getString(MediaMetadata.METADATA_KEY_GENRE);
        String newGenre = metadata.getString(MediaMetadata.METADATA_KEY_GENRE);

        track.metadata = metadata;

        // if genre has changed, we need to rebuild the list by genre
        if (!oldGenre.equals(newGenre)) {
            buildListsByGenre();
        }
    }
    ...

**Comment by mangini** [comment]
Not really. MutableMediaMetadata is, well... a mutable object. When we assign "track.metadata = metadata", we are effectively updating the "metadata" attribute on the corresponding MutableMediaMetadata object wherever it is referenced. Since, for a given mediaId, we use the same object on both mMusicListById and mMusicListByGenre, both maps will always point to the up to date object.

We only have special treatment for the mMusicListByGenre because genre is a key on it, and if it changes, we need to re-bucket the value object. We obviously assume that mediaId doesn't change, otherwise we would need to give special treatment to mMusicListById too.
