### ISSUE TITLE
Failed to find resource for a few 9-patch images

### ISSUE THREAD

**Issue by rabyunghwa** [googlesamples/android-UniversalMusicPlayer#47]
Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').

**Comment by mangini** [comment]
This is likely caused by a compatibility issue between play services and another library in your project. I just updated the project dependencies to use the new play services, which should fix this for you. Please, reopen if it is not fixed.
