### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nico281** [googlesamples/android-UniversalMusicPlayer#48]
Hi, 
Mi name is Nicolas. Im doing my project degree for System engineer. 
I want to integrate the music player in my project but only the music player itself and not the nav drawer with the search. I want to open a mp3 and use the music player only. 
It is posible to have a hand on this? because the whole musicplayer project has a lot of clases and i dont know where to start, i dont know the things i need to take out etc.
If any of you could help me it could be great.

Cheers!!!

**Comment by mangini** [comment]
I suggest you ask on stackoverflow, since this area is used for the project team to track issues and feature requests. The actual playback is handled by the MediaPlayer from the Android media framework (see the MusicService class).
