### ISSUE TITLE
Is nulling of references realy necessary?

### ISSUE THREAD

**Issue by PaulWoitaschek** [googlesamples/android-UniversalMusicPlayer#51]
I just had a discussion with a collegue about manually nulling callbacks to prevent memory leaks.

He referred to this project where excacly that is done [here](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/ui/MediaBrowserFragment.java#L204).

````java
@Override
public void onDetach() {
    super.onDetach();
    mMediaFragmentListener = null;
}
````

Is this necessary?

**Comment by mangini** [comment]
This is a hot discussion topic, for which, AFAIK, there is no one-size-fits-all answer. In general, I nullify references to resource intensive objects. It will eventually be handled by GC, but the minor readability impact is worth the risk of a memory leak caused by a dangling reference.

**Comment by joezorry** [comment]
If there is a chance of a lingering reference then null it, otherwise don't.
Latest fragmented podcast talks about this.
Context leaks in android are bad... really bad.
