### ISSUE TITLE
Not getting Thumb with Genres

### ISSUE THREAD

**Issue by SopMar** [googlesamples/android-UniversalMusicPlayer#53]
I am using UMP example provided by you, I have not made any change in my code, even I have not tried anything out of the box, I just imported your project into my work-space and checked it on my device, and found that I am not getting Thumb with Genres (Songs by genre) and List of Genres... 

Whereas I supposed to get Thumb from our JSON, here is what I have tried (but no success) -
holder.mImageView.setImageBitmap(description.getIconBitmap());

**Comment by ganesh2shiv** [comment]
Are you saying you want to show some thumbnail before the genre title in the list?

Something like this?
![screenshot](https://cloud.githubusercontent.com/assets/1255749/12552598/bae1dcca-c398-11e5-8864-dad62d17657d.png)

If yes, you can put this code in the [MediaItemViewHolder.java](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/ui/MediaItemViewHolder.java#L97-L98) file
```java
default:
    holder.mImageView.setVisibility(View.GONE);
    if (description.getTitle().toString().equalsIgnoreCase("Rock")) {
        holder.mImageView.setImageDrawable(
                activity.getDrawable(R.drawable.ic_rock_genre));
        holder.mImageView.setVisibility(View.VISIBLE);
    } else if (description.getTitle().toString().equalsIgnoreCase("Cinematic")) {
        holder.mImageView.setImageDrawable(
                activity.getDrawable(R.drawable.ic_cinematic_genre));
        holder.mImageView.setVisibility(View.VISIBLE);
    } else if (description.getTitle().toString().equalsIgnoreCase("Jazz & Blues")) {
        holder.mImageView.setImageDrawable(
                activity.getDrawable(R.drawable.ic_jazz_genre));
        holder.mImageView.setVisibility(View.VISIBLE);
    }
```
and put the icons **ic_rock_genre**, **ic_cinematic_genre**, and **ic_jazz_genre** in the drawables folder.

Or you can load the icons from the network using some third party library like Picasso.
```java
default:
    holder.mImageView.setVisibility(View.GONE);
    if (description.getTitle().toString().equalsIgnoreCase("Rock")) {
        Picasso.with(activity).load("https://raw.githubusercontent.com/google/material-design-icons/master/av/drawable-hdpi/ic_surround_sound_black_36dp.png").into(holder.mImageView);
        holder.mImageView.setVisibility(View.VISIBLE);
    } else if (description.getTitle().toString().equalsIgnoreCase("Cinematic")) {
        Picasso.with(activity).load("https://raw.githubusercontent.com/google/material-design-icons/master/av/drawable-hdpi/ic_web_black_36dp.png").into(holder.mImageView);
        holder.mImageView.setVisibility(View.VISIBLE);
    } else if (description.getTitle().toString().equalsIgnoreCase("Jazz & Blues")) {
        Picasso.with(activity).load("https://raw.githubusercontent.com/google/material-design-icons/master/av/drawable-hdpi/ic_movie_black_36dp.png").into(holder.mImageView);
        holder.mImageView.setVisibility(View.VISIBLE);
    }
```
Hope it helps.

**Comment by SopMar** [comment]
@ganesh2shiv Thank you so much for this incredible work :)

**Comment by devshisiyani** [comment]
the code you have pasted above does not compile at the latest code in MediaItemViewHolder.java
The lastest java code uses class Drawable
any chance of providing snippet code for  put the icons ic_rock_genre, ic_cinematic_genre, and ic_jazz_genre in the drawables folder
thank
