### ISSUE TITLE
Audio does not buffer enough before starting playback

### ISSUE THREAD

**Issue by richardmitic** [googlesamples/android-UniversalMusicPlayer#54]
Using a Nexus 5X (Android 6.0.1) the audio quite often stutters at the beginning of a song. Logcat produces a sequence of 701 (MEDIA_INFO_BUFFERING_START) and 702 (MEDIA_INFO_BUFFERING_END) state messages from the MediaPlayer class, indicating that the internal buffer is being emptied and filled again. The problem does not occur using an HTC One running Android 5.02.

Could this be an issue deeper in the MediaPlayer class? It seems similar to this https://code.google.com/p/android/issues/detail?id=196122

**Comment by sachins** [comment]
It would be great to have an option to switch to ExoPlayer in place of MediaPlayer.

**Comment by mangini** [comment]
It's a good idea, @sachins , my concern is that it would make the app more complex and distract developers from the main goal of this reference app, which is to showcase the MediaSession/MediaBrowserService APIs and how to support multiple formfactors. I would rather keep it using MediaPlayer only, although if you fork a version to use ExoPlayer, feel free to post it here.

**Comment by mangini** [comment]
@richardmitic: there is not much you can do to change MediaPlayer buffer size, unfortunately. But if you can fetch the remote song using a HTTP client, you can pipe it into a data structure, implement a clever MediaDataSource and use it instead of a URL on mediaPlayer.setDataSource().
