### ISSUE TITLE
Can i play .m3u?

### ISSUE THREAD

**Issue by vlad-redL1ne** [googlesamples/android-UniversalMusicPlayer#55]
Hi. I'd like this player and i have some questions:
1. How can i play stream music from .m3u file ? Is it possible?
2. If it possible to play .mp3 file from url ?

**Comment by mangini** [comment]
1) m3u is just a text file with a list of media files. You should be able to read line by line and transform it into a MediaSession queue.
2) yes, that's what this app does. If you look at https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L285  you will see that it fetches the songs from a remote server. Just replace them with yours.

**Comment by adetheprince** [comment]
Only music saved youtube works? my own music stored on my server dont play at all? 
Please help me .
