### ISSUE TITLE
How i open on android studio

### ISSUE THREAD

**Issue by calvinn** [googlesamples/android-UniversalMusicPlayer#56]
how i open it on android studia and make a .apk

**Comment by CoolGames** [comment]
Read http://developer.android.com/samples/index.html to find out.

I am trying this app but it seems to want API 23 - 6.0 and I have API 22 - 5.1.1
New to developing with Android Studio.
Where is the API setting made ?

**Comment by mangini** [comment]
It is in [build.gradle](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/build.gradle). You should be able to compile with API 22, although I recommend you to update to API 23 (note that it is backward compatible with API 21, so even if you compile with 23, you should still get it to run on phones running 21)
