### ISSUE TITLE
 Retrieve media item source

### ISSUE THREAD

**Issue by ismaeltoe** [googlesamples/android-UniversalMusicPlayer#57]
I want to allow users download songs. I put a "Download" in the list view that displays the songs. So, when clicking on "Download" I have to retrieve the song URL.

I tried:
```java
MediaMetadata track = mMusicProvider.getMusic(MediaIDHelper.extractMusicIDFromMediaID(item.getDescription().getMediaId()));
String source = track.getString(MusicProvider.CUSTOM_METADATA_TRACK_SOURCE);
```

but got a NullPointerException on the second line.

**Comment by ufarooq** [comment]
Do you have any update on this? I have an exact issue...
