### ISSUE TITLE
UniversalMusicPlayer

### ISSUE THREAD

**Issue by pranav0641** [googlesamples/android-UniversalMusicPlayer#58]
When i Run this app in android studio the following error comes:

Error:A problem occurred configuring project ':mobile'.
> Could not resolve all dependencies for configuration ':mobile:_debugCompile'.
   > Could not resolve com.github.amlcurran.showcaseview:library:5.0.0.
     Required by:
         android-UniversalMusicPlayer-master:mobile:unspecified
      > Could not resolve com.github.amlcurran.showcaseview:library:5.0.0.
         > Could not get resource 'https://jcenter.bintray.com/com/github/amlcurran/showcaseview/library/5.0.0/library-5.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/amlcurran/showcaseview/library/5.0.0/library-5.0.0.pom'.
               > jcenter.bintray.com

Please Provide a solution as soon as possible.............

**Comment by mangini** [comment]
This sounds like your environment not being able to reach jcenter.bintray.com. See if you have any antivirus blocking gradle or Android Studio to connect to jcenter.
