### ISSUE TITLE
MediaDetailsFragment missing

### ISSUE THREAD

**Issue by fernandomantoan** [googlesamples/android-UniversalMusicPlayer#6]
The layout file `media_details_activity.xml` refers to a fragment `com.example.android.uamp.ui.tv.MediaDetailsFragment` that isn't present in the source code.

**Comment by mangini** [comment]
Fixed by https://github.com/googlesamples/android-UniversalMusicPlayer/commit/cafb5c17a80e0788afc4ceca271574c3302f79a0
