### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException 

### ISSUE THREAD

**Issue by mohanrajsambath** [googlesamples/android-UniversalMusicPlayer#60]
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation Indexing started at: java.lang.Throwable at com.intellij.openapi.project.DumbServiceImpl.scheduleCacheUpdate(DumbServiceImpl.java:160) at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:85) at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:300) at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:421) at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:57) at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:114) at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:127) at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:359) at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:951) at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1800(ModuleManagerImpl.java:73) at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:857) at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1600(ModuleManagerImpl.java:619) at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:610) at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:48) at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:37) at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.commitModel(ModuleRootManagerImpl.java:178) at com.intellij.openapi.roots.impl.RootModelImpl.commit(RootModelImpl.java:338) at com.intellij.openapi.roots.ModuleRootModificationUtil$8.run(ModuleRootModificationUtil.java:167) at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002) at com.intellij.openapi.roots.ModuleRootModificationUtil$10.run(ModuleRootModificationUtil.java:208) at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:716) at com.intellij.openapi.roots.ModuleRootModificationUtil.doWriteAction(ModuleRootModificationUtil.java:205) at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:164) at com.intellij.openapi.roots.ModuleRootModificationUtil.setModuleSdk(ModuleRootModificationUtil.java:123) at org.jetbrains.android.sdk.AndroidSdkUtils.tryToSetAndroidPlatform(AndroidSdkUtils.java:469) at org.jetbrains.android.sdk.AndroidSdkUtils.setupPlatform(AndroidSdkUtils.java:485) at org.jetbrains.android.sdk.AndroidSdkUtils.setupAndroidPlatformIfNecessary(AndroidSdkUtils.java:675) at org.jetbrains.android.facet.AndroidFrameworkDetector.doImportSdkAndFacetConfiguration(AndroidFrameworkDetector.java:107) at org.jetbrains.android.facet.AndroidFrameworkDetector$1$1.run(AndroidFrameworkDetector.java:97) at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150) at org.jetbrains.android.facet.AndroidFrameworkDetector$1.run(AndroidFrameworkDetector.java:94) at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:342) at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:58) at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:165) at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150) at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:162) at com.intellij.ide.startup.impl.StartupManagerImpl.access$1000(StartupManagerImpl.java:58) at com.intellij.ide.startup.impl.StartupManagerImpl$4.run(StartupManagerImpl.java:196) at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:318) at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52) at com.intellij.openapi.project.DumbServiceImpl$10.run(DumbServiceImpl.java:503) at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744) at java.awt.EventQueue.access$400(EventQueue.java:97) at java.awt.EventQueue$3.run(EventQueue.java:697) at java.awt.EventQueue$3.run(EventQueue.java:691) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) at java.awt.EventQueue.dispatchEvent(EventQueue.java:714) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) -----------------------------

**Comment by mangini** [comment]
I'm not sure what this is about. When did you get this exception? What should we change? By the exception message, it seems you tried to do something, like run the project, before Android Studio finished building its indexes. If that's the case, you should just wait a bit more.
