### ISSUE TITLE
Direct to Genre List

### ISSUE THREAD

**Issue by zahid--ali** [googlesamples/android-UniversalMusicPlayer#62]
How can i start the project directly form the genre list neither from the genre top view. I want the app to start from list inside genre.

**Comment by erautenberg** [comment]
I was trying to figure out the same thing, but I am also having an issue determining how to add more levels, for example, a genre, then a sub-genre (Genre/Comedy/Sketch Comedy).

**Comment by mangini** [comment]
The navigation levels are defined by the hierarchy returned by MediaBrowserService. If you want to change the hierarchy, just change the code in https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L282

**Comment by erautenberg** [comment]
Thanks, I did find that, but it doesn't seem as easy as just adding to that function.  I also have to understand the way the Collections work and it seems like there needs to be another hashmap, or a hashmap containing a hashmap?  At least that's how I'm interpreting how the getGenres function and the mMusicListByGenre hash map works.  It seems like adding just one more level actually involves delving much deeper into the entire structure.

**Comment by chetnapriyadarshini** [comment]
@erautenberg  I am in the same situation, did you end up adding a level? If so how?
