### ISSUE TITLE
No Logs are displayed

### ISSUE THREAD

**Issue by xtools-at** [googlesamples/android-UniversalMusicPlayer#64]
Hi,

I was wondering if you can see the Log-messages called by LogHelper.
My build variant is Debug, but Logcat (both Android Studio and ADB) does not show me any messages, which are called via LogHelper... Everything else is there.
Does anyone have an idea what I'm doing wrong?

Many thanks in advance!

**Comment by xtools-at** [comment]
never mind, found a workaround

**Comment by Kassinaudio** [comment]
Hi,
I have the same problem than you, ( LogCat does not show me any messages),
Build Variant : Debug, no filters, and Mode Verbose in Logcat. 
I'm a total nob, and if you had any information about this issue, I would be very grateful.

Thanks

**Comment by xtools-at** [comment]
Check this file:
https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/utils/LogHelper.java

and then comment out the if-clause for v and d:
```
 public static void v(String tag, Object... messages) {
        // Only log VERBOSE if build type is DEBUG
        if (BuildConfig.DEBUG) {
            log(tag, Log.VERBOSE, null, messages);
        }
    }
```
to
```
 public static void v(String tag, Object... messages) {
        // Only log VERBOSE if build type is DEBUG
        //if (BuildConfig.DEBUG) {
            log(tag, Log.VERBOSE, null, messages);
        //}
    }
```

Worked for me!

Bests, Martin
