### ISSUE TITLE
"Error loading media" when starting from recent apps

### ISSUE THREAD

**Issue by xtools-at** [googlesamples/android-UniversalMusicPlayer#66]
Since the latest commits from Feb 25, 2016, the app says "Error loading media" when bringing it back from Recent Apps or after Resume when the screen went out - if you are not in the root category.

To reproduce this, browse into Genres and press the home button, then restart from recent apps.
It seems that it fetches the JSON every time now, and the results aren't there in time for the onLoadChildren-Call. Here's a part of my logcat:

03-06 10:49:51.461 18534-18534/com.example.android.uamp I/uamp_MusicService: OnGetRoot: clientPackageName=com.example.android.uamp; clientUid=10147 ; rootHints=null
03-06 10:49:51.468 18534-18534/com.example.android.uamp I/uamp_BaseActivity: onConnected
03-06 10:49:51.469 18534-18534/com.example.android.uamp I/uamp_BaseActivity: connectionCallback.onConnected: hiding controls because metadata is null
03-06 10:49:51.469 18534-18534/com.example.android.uamp I/uamp_BaseActivity: hidePlaybackControls
03-06 10:49:51.469 18534-18534/com.example.android.uamp I/uamp_PlaybackControlsF: onConnected, mediaController==null? false
03-06 10:49:51.469 18534-18534/com.example.android.uamp I/uamp_PlaybackControlsF: onMetadataChanged null
03-06 10:49:51.469 18534-18534/com.example.android.uamp I/uamp_PlaybackControlsF: onPlaybackStateChanged PlaybackState {state=0, position=0, buffered position=0, speed=1.0, updated=41308383, actions=3124, error=null, custom actions=[], active item id=-1}
03-06 10:49:51.471 18534-18534/com.example.android.uamp I/uamp_MusicService: OnLoadChildren: parentMediaId=__BY_GENRE__
03-06 10:49:51.471 18534-18534/com.example.android.uamp I/uamp_MediaBrowserFragm: fragment onChildrenLoaded, parentId=__BY_GENRE__  count=0
03-06 10:49:51.474 18534-18534/com.example.android.uamp I/uamp_MediaBrowserFragm: checkForUserVisibleErrors. forceError=true showError=true isOnline=true
03-06 10:49:51.824 18534-18935/com.example.android.uamp I/uamp_RemoteJSONSource: Found music track: {"title":"Jazz in Paris","album":"Jazz & Blues","artist":"Media Right Productions","genre":"Jazz & Blues","source":"Jazz_In_Paris.mp3","image":"album_art.jpg","trackNumber":1,"totalTrackCount":6,"duration":103,"site":"https:\/\/www.youtube.com\/audiolibrary\/music"}

**Comment by aminezghidi** [comment]
I'm facing the same problem.
