### ISSUE TITLE
Music dont play and I get mediaplayer error 38 or so

### ISSUE THREAD

**Issue by adetheprince** [googlesamples/android-UniversalMusicPlayer#68]
I have changed the sample url on the RemotJsonSource to (http://satdoc.dyndns.info/music.json)
I saw all the list names showing, but when I tried to play the mp3 It gives me error.
Can anyone tell me what I am doing wrong (My music is not playing but the demo playes fine) ?
The demo I mean http://storage.googleapis.com/automotive-media/music.json.
is there anything else need to be done on the remote end?
all songs (mp3) is uploaded to http://satdoc.dyndns.info/music/.
Please help a noob here.
Finally where do I find documentation or tutorial?.
Thanks in advance.

**Comment by mangini** [comment]
Make sure your mp3 files are in the right place and have the right name and correct permission. According to your json (http://satdoc.dyndns.info/music.json), there should be a song in http://satdoc.dyndns.info/Vespers.mp3, but that url returns 404. Bear in mind that uAmp is not a final, baked user product. It is instead a source of code patterns for developers.

**Comment by adetheprince** [comment]
Hi there
Really thanks for your reply and sorry for double post as I thought I was not clear about my question.
Also I am sure this is not a finished product but as an android learner I am testing many media player codes to compere and learn on my way.
I am sure the link for the song was Ok, but I will try again and see if I mistaken the path for the music.
Thank you again and sorry got the trouble.
