### ISSUE TITLE
Request: make it work on pre-Lollipop versions of Android

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-UniversalMusicPlayer#7]
Lollipop (API 21) is running on about 3.3% according to the current statistics (from here: https://developer.android.com/about/dashboards/index.html ) .

The sample works only from this API level. On previous, it crashes.

If Google tried to show here how to address as many devices and screens, this sample works on a very small fraction of the available ones.

Please make it support the majority of devices out there.

**Comment by gafanhotz** [comment]
The detail is that Google focused it to Auto, Wear, Tablets and Phones, and some of these are Lollipop only. I don't think Google is gonna change it.

**Comment by ardock** [comment]
And they already shared [another great sample](http://android-developers.blogspot.com.es/2014/07/google-io-2014-app-source-code-now.html) for [that](http://android-developers.blogspot.com.es/2014/08/material-design-in-2014-google-io-app.html).

I personally prefer their decision, statistics will change fast and there are other as Rusty Rants points [here](http://rustyshelf.org/2014/12/17/2015-the-year-of-android/) 

> If you launch an app today you can target Android 4.1 and above, and have access to far more users than the entirety of the iOS platform. If you really want to go Android 5.0 only, you can do that too. All of the Nexus devices, as well as high profile ones from LG, Motorola and many others are currently seeing Android 5.0 being rolled out to them.

and [here](http://rustyshelf.org/2015/01/31/how-new-versions-of-android-work/)

> So while Android 5.0 has less than 1% adoption in the overall Android eco-system, 23% of our customers already run it.

**Comment by AndroidDeveloperLB** [comment]
It's supposed to work on as many devices and platforms out there.
I think there are way more tablets and smartphones running pre-Lollipop Android than all others combined.

Also, what about ChromeCast casting? does the app support it? if so, that's another reason why it should work on pre-Lollipop.

**Comment by sues-lee** [comment]
I think it's very helpful to make it to work on Android 4.x . I made a simple [APP](https://github.com/sues-lee/SuesNews) to train how to use new features in Android 5.x on Android 4.x, but some of the new  features is hard to achieve. So I really wanna know will Google do if they make it support pre-Lollipop.

**Comment by AndroidDeveloperLB** [comment]
@sues-lee That's true. Kitkat is much more popular than Lollipop now.

**Comment by Zordid** [comment]
I also would like to see a new app that targets Android 5 and 4(.4 at least)!
Reason is that I think Google I/O app is great for inspiration, but it also has some serious defects I think. It is not really what an app should look like today... :(

**Comment by jlelse** [comment]
I tried to fork and change to pre-lollipop but it wasn't possible because this app uses so much lollipop api's :(

**Comment by mangini** [comment]
Our reasoning was to first showcase the new API's. Having said that, showing best practices to support media API's on L **and** pre-L is on our list, so stay tuned.

I will leave this issue open, so I can keep you updated.

**Comment by AndroidDeveloperLB** [comment]
@mangini Wow, thank you.

**Comment by flexpeace** [comment]
Thanks a lot, we are looking forward to it.

**Comment by chrisanderson79** [comment]
If anyone is interested and can't wait for the official support release I’ve got a pre-lollipop version working that’s build off the compat libraries (plus a custom compat MediaBrowser library that I had to build):

https://github.com/chrisanderson79/android-UniversalMusicPlayer

This is 100% unofficial so I offer no guarantees.

**Comment by AndroidDeveloperLB** [comment]
@chrisanderson79 MinAPI 14 . Well done !

**Comment by nournia** [comment]
+1

**Comment by gafanhotz** [comment]
Yeah, because, let's support a EOL Android version. Congrats, you're part of the problem of why Android is fragmented.

**Comment by AndroidDeveloperLB** [comment]
How could supporting most of the devices out there be a bad thing? Even Google keeps publishing support libraries for API 7 and above (today it got a new update), so much that it's almost a must to use them.

**Comment by jjvargas** [comment]
+1 Thanks for sharing

**Comment by jssingh** [comment]
@mangini Any progress on support for API 16 (and above)? Please let us know, thanks!

**Comment by KamranMackey** [comment]
@jssingh Use @chrisanderson79's fork. It works with API 14 and above.

**Comment by PaoloRotolo** [comment]
Any news on this? I want to make an app based on this player and I need pre-Lollipop support...

**Comment by anhnt** [comment]
That worked. Thanks @chrisanderson79 . Please be noted that this app use com.android.support:leanback-v17:22.1.1 which supports minSdkVersion=17, so this app will support this as well, not API Level 14. 

Cheers!

**Comment by code-read** [comment]
Thanks, @chrisanderson79, with your fork I can test this app on my LG LGLS660 phone and my Samsung Tab 4, both purchased this year, both running Kitkat.  Thanks to AndroidDeveloperLB for articulating this issue better than I could have.

**Comment by rainman20** [comment]
>I will leave this issue open, so I can keep you updated.
@mangini any update about this?

**Comment by tchoulihan** [comment]
I just went through this also. Here's a branch I just went through a shitload to fix for api-14:

https://github.com/tchoulihan/android-UniversalMusicPlayer/tree/api_14

**Comment by chrisanderson79** [comment]
@tchoulihan is this supposed to be different from the fork I made? You only seem to have changed a few files by commenting things out, also you might want to take out some of my comments if you're trying to pass it off as your own work? https://goo.gl/wqc9cz

**Comment by tchoulihan** [comment]
Would you like me to submit a pull request to yours? Yours didn't work out of the box for me.

**Comment by chrisanderson79** [comment]
If you found issues with the fork that I made then let me know, I can take a look when I get the time.

**Comment by henrydvq** [comment]
I am new to programming, but get very far ... now, I hope someone can tell me how to add playlist .. I'm stuck in this.

**Comment by jssingh** [comment]
I am surprised the project still hasn't been updated to use MediaBrowserCompat yet. I thought 23.1.1 brought along this class that allows for this sample to go back to API 14 and above. Pinged Ian Lake on twitter(@ianhlake) and he mentioned that he is writing a blog post on how to do it. Don't think that ever happened, but he talked about it at the Big Android BBQ (https://www.youtube.com/watch?v=XQwe30cZffg).

Can we expect that to happen anytime soon?
Thanks!

**Comment by b95505017** [comment]
I think that we have to wait until MediaBrowserCompat & service change to public API.

**Comment by mangini** [comment]
Official support for the Media support library (MediaBrowserCompat) is coming out pretty soon.

**Comment by nickh364** [comment]
MediaBrowserCompat is out http://android-developers.blogspot.com/2016/02/android-support-library-232.html

**Comment by mangini** [comment]
I just uploaded a few commits that add support for mediabrowsercompat and all other compat libraries that allow uAmp to work at least on v17. Sorry for the long time to get this out, but we were waiting for official media support library. Hope it helps!

**Comment by b95505017** [comment]
Thanks! Just wondering which components needs v17 API?
I thought that Media support library should work on v4.

**Comment by raeve92** [comment]
@b95505017  Actually, the app requires v17 API because Android TV and 'leanback' library, if you remove it or separate in another application module, you can downgrade the version.
