### ISSUE TITLE
Music Player Does Not Update MediaMetadataCompat

### ISSUE THREAD

**Issue by izbrannick** [googlesamples/android-UniversalMusicPlayer#71]
If data changed, music player would not update displaying data, need to kill app before it takes new values:

example:
{ "title" : "Jazz in Paris",
	  "album" : "Jazz & Blues",
	  "artist" : "Media Right Productions",
	  "genre" : "Jazz & Blues",
	  "source" : "Jazz_In_Paris.mp3",
	  "image" : "album_art.jpg",
	  "trackNumber" : 1,
	  "totalTrackCount" : 6,
	  "duration" : 103,
	  "site" : "https://www.youtube.com/audiolibrary/music"
	}

JSON data updated to:
{ "title" : "Other Other",
	  "album" : "Jazz & Blues",
	  "artist" : "Media Right Productions",
	  "genre" : "Jazz & Blues",
	  "source" : "Jazz_In_Paris_2.mp3",
	  "image" : "album_art.jpg",
	  "trackNumber" : 2,
	  "totalTrackCount" : 6,
	  "duration" : 203,
	  "site" : "https://www.youtube.com/audiolibrary/music"
	}

P.S
I want to use is as a radio player, and need to update Title and other data while streaming...

**Comment by adetheprince** [comment]
Hi there
I am in the same boat like you, is it possible if you can help me on how did you manage to play music that stored on your server?
Example like this:

example:
{ "title" : "Jazz in Paris",
"album" : "Jazz & Blues",
"artist" : "Media Right Productions",
"genre" : "Jazz & Blues",
"source" : "mytest.mp3",
"image" : "my_art.jpg",
"trackNumber" : 1,
"totalTrackCount" : 6,
"duration" : 103,
"site" : "http/mysite.com/music"
}

I am sorry to ask you as the author didn't reply for long.
Thanks

**Comment by mangini** [comment]
@izbrannick : uAmp was designed to support a static library of songs. You can adapt it to support your use case, though. You might need to change MusicProvider and related /model/ classes, and call mediaSession.updateMetadata whenever the metadata (title/art/etc) changes. I will close this bug as this is out of scope, but feel free to continue the conversation here if you want.

**Comment by izbrannick** [comment]
@mangini thank you for your reply. I agree with you that it is not a bug, but more like a feature request.
Could you please be more specific about how to update mediaSession? Thx in advance

**Comment by CCorrado** [comment]
I have this same idea, I use the underlying UAMP code to control the media states of a list of audio files. The app I've written also gives the users ability to download/remove the audio files while they're in the app, which means the "static list" of songs never gets updated. I attempted to hack the media session by running the async task to update the media library but with no luck, the media session seems to need to be killed and restarted.... is there no "notifyDataSetChanged" within media session like there is in a RecyclerView or ListView?? This is a lot of complex code to not really do a whole lot..
