### ISSUE TITLE
How to play music are from you server?

### ISSUE THREAD

**Issue by adetheprince** [googlesamples/android-UniversalMusicPlayer#72]
I am trying to test this but didn't work anyone can help me?

example:
{ "title" : "Jazz in Paris",
"album" : "Jazz & Blues",
"artist" : "Media Right Productions",
"genre" : "Jazz & Blues",
"source" : "mytest.mp3",
"image" : "my_art.jpg",
"trackNumber" : 1,
"totalTrackCount" : 6,
"duration" : 103,
"site" : "http/mysite.com/music"
}

**Comment by mangini** [comment]
Please, don't open duplicate bugs. See my response on https://github.com/googlesamples/android-UniversalMusicPlayer/issues/68
