### ISSUE TITLE
Memory Leak issue : com.example.android.uamp.ui.FullScreenPlayerActivity has leaked

### ISSUE THREAD

**Issue by TonyTangAndroid** [googlesamples/android-UniversalMusicPlayer#75]
I have been working on an music player app based on this sample. And I have had installed LeakCanary to detect memory leak issue and find out that there is indeed a memory leak issue.  Please refer to the following information for details:

> In com.example.android.uamp:1.1:2.
* com.example.android.uamp.ui.FullScreenPlayerActivity has leaked:
* GC ROOT static android.os.UserManager.sInstance
* references android.os.UserManager.mContext
* references android.app.ContextImpl.mOuterContext
* references com.example.android.uamp.MusicService.mConnections
* references android.support.v4.util.ArrayMap.mArray
* references array java.lang.Object[].[2]
* references android.os.Handler$MessengerImpl.this$0
* references android.support.v4.media.MediaBrowserCompat$CallbackHandler.mCallbackImpl
* references android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi23.mBrowserObj
* references android.media.browse.MediaBrowser.mContext
* leaks com.example.android.uamp.ui.FullScreenPlayerActivity instance
* Retaining: 631 KB.
* Reference Key: 21cd0054-506d-4c6f-94d1-47090c16fbb0
* Device: LGE google Nexus 5 hammerhead
* Android Version: 6.0.1 API: 23 LeakCanary: 1.4-beta1 02804f3
* Durations: watch=5024ms, gc=121ms, heap dump=6019ms, analysis=40029ms

You could also refer to the [link](https://www.dropbox.com/s/h6b4x1jib2r6cte/Dump_memory_Leak_UniversalMusicPlayer.hprof?dl=0) for the dump hprof file.

**Comment by shareyourlocationsite** [comment]
@TonyTangAndroid I've the same problem here. Do you have any progress with this?

**Comment by TonyTangAndroid** [comment]
Sadly no. I have submitted a bug here https://code.google.com/p/android/issues/detail?id=205220 . Hopefully they will get it fixed in the next release.

**Comment by molexx** [comment]
I think this is fixed now - 205220 is marked 'released' and LeakCanary is no longer flagging this for me.

**Comment by smishra2** [comment]
Thanks, molexx!
