### ISSUE TITLE
How to read musics in local directory ?

### ISSUE THREAD

**Issue by Sanosukeyy** [googlesamples/android-UniversalMusicPlayer#77]
Hi,

I very love your work. Just for my personal utilisation, I want to read my own music on local directory. Anyone can help me to find the way to change the source ?

Thanks a lot mates.

**Comment by mangini** [comment]
It should not be hard. In general terms, you should implement a new [MusicProviderSource](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProviderSource.java) that uses the MediaStore content provider (you can borrow some code from [this sample](https://android.googlesource.com/platform/development/+/master/samples/RandomMusicPlayer/src/com/example/android/musicplayer/MusicRetriever.java)). Then, replace the default MusicProviderSource in [MusicProvider constructor](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L71).
