### ISSUE TITLE
How to add songs by Artists

### ISSUE THREAD

**Issue by arushk1** [googlesamples/android-UniversalMusicPlayer#80]
I wanted to know how to add songs sorted by artists rather than Genres

Thanks

**Comment by mangini** [comment]
Most logic for the category type (GENRE, SEARCH) is in [MusicProvider.java](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java). There are a few extra pieces in [QueueHelper.java](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/utils/QueueHelper.java)
