### ISSUE TITLE
unable to play audio using own app id..

### ISSUE THREAD

**Issue by arpitjoshi08** [googlesamples/android-UniversalMusicPlayer#82]
hello sir , i am using this code with my app id .. and i follow all steps according to doc and also register my chromecast device on console but my video is running some time and also audio not playing using this sample ..please help ..

**Comment by mangini** [comment]
To be able to help, I will need a stack trace and/or more technical details. Also, this app shows no video, only audio. If your video is running, you are using a different app. Closing this bug, feel free to reopen it if you have more concrete technical data and you are sure you are using this sample app and not something else.
