### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by calvinnie12** [googlesamples/android-UniversalMusicPlayer#85]
If i open the app i get this  http://prntscr.com/bap1by

I run on android 4.2

**Comment by nickh364** [comment]
Try updating cast companion library to 2.8.4 and the support libraries to 23.2.1 or newer.

**Comment by calvinnie12** [comment]
How i update that

**Comment by nickh364** [comment]
Under the moble folder in the build.gradle file. You can see the changes here https://github.com/googlesamples/android-UniversalMusicPlayer/pull/79/files

**Comment by calvinnie12** [comment]
http://prntscr.com/bbi26z

**Comment by calvinnie12** [comment]
http://prntscr.com/bbi2jp

**Comment by nickh364** [comment]
It should look something like this:
dependencies {
    compile 'com.google.android.gms:play-services-cast:8.4.0'
    compile 'com.google.android.support:wearable:1.3.0'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:cardview-v7:23.2.1'
    compile 'com.android.support:mediarouter-v7:23.2.1'
    compile 'com.android.support:leanback-v17:23.2.1'
    compile 'com.google.android.libraries.cast.companionlibrary:ccl:2.8.4'
    compile 'com.android.support:design:23.2.1'
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support:support-annotations:23.2.1'
    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
}

**Comment by mangini** [comment]
I just updated all support libraries, gradle, gradle plugin, cast and ccl. Please, update it, take a look and reopen the bug if you still have issues. Make sure you have all Android SDK up to date. (Android Studio -> Tools -> Android -> SDK Manager -> Launch Standalone SDK Manager -> Install XX packages, if the button is enabled).
