### ISSUE TITLE
Exception of Attribute "dotRadius" already defined with incompatible format.

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-UniversalMusicPlayer#87]
Hi-I tried to change the Android support libraries version(to 24.0.0), but it occurs some exception.

C:\Users~\Downloads\Compressed\UniversalMusicPlayer\mobile\build\intermediates\res\merged\debug\values\values.xml
**Error:(352) Attribute "dotRadius" already defined with incompatible format.
Error:(335) Original attribute defined here.**
Error:Execution failed for task ':mobile:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users~\Android\Android-Sdk\build-tools\24.0.0\aapt.exe'' finished with non-zero exit value 1

**Comment by davidmonti** [comment]
I have the same problem here, is it a problem with the update?

**Comment by YiloPo** [comment]
Yeah

**Comment by davidmonti** [comment]
The problem is the wearable compat library is incompatible with the leanback one, there is probably another way to fix it but i just removed the wearable library and its references since i was not using them anyway

**Comment by TreeFrogApps** [comment]
Thanks for the tip .. was driving me crazy!

**Comment by CCorrado** [comment]
+1 having this issue too.... so annoying

**Comment by ursimon** [comment]
I have the same issue.

**Comment by vktaras** [comment]
Thanks +1

**Comment by nomad811** [comment]
+1

**Comment by Mugurell** [comment]
SDK 25 solves this

**Comment by nic0lette** [comment]
After the support library was updated I think this issue is obsolete. Please reopen it if there are continuing problems.
