### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by krzysiekbielicki** [googlesamples/android-UniversalMusicPlayer#9]
There are no tests in src/test nor src/androidTest

**Comment by addyosmani** [comment]
Similar feedback over in https://twitter.com/passy/status/577444787156045824. Sure this was an oversight, but would be interesting to hear if there are plans for tests at some point.

**Comment by mangini** [comment]
@krzysiekbielicki and @addyosmani: yes, we are working on publishing our tests. Thanks for the feedback!

**Comment by keyboardsurfer** [comment]
If you're looking for a sample with tests, feel free to take a look at [Topeka](http://github.com/googlesamples/android-topeka).

**Comment by mangini** [comment]
We added unit and instrumented tests in https://github.com/googlesamples/android-UniversalMusicPlayer/commit/680500966876e135a86f9cea83fde6fba5137f50
